### ISSUE TITLE
Consuming on a channel uses 100% CPU

### ISSUE THREAD

**Issue by kureuil** [sozu-proxy/lapin#102]
While running the example `client` of the `lapin-futures` crate, the CPU usage stays at 100%, when it should be passively waiting for I/O readiness.

I believe that the commit that introduced this bug is bf6913c where the current task is rescheduled when a delivery couldn't be found in the transport's connection.

**Comment by Keruspe** [comment]
That's probably this commit indeed.
I fail to understand when we're suppose to explicitely park ourselves and when we do not, documentation is quite sparse in this regard.
