### ISSUE TITLE
Basic consume doesn't use RabbitMQ generated consumer tag

### ISSUE THREAD

**Issue by kureuil** [sozu-proxy/lapin#112]
RabbitMQ Version: 3.6 & 3.7
Lapin version: a8ac2b2577c6c29db49fcfdf8de0a04dacccdb41

When creating a consumer with an empty consumer tag, RabbitMQ generates one and returns it to the client: lapin-async gets it and create its consumer appropriately however lapin-futures just uses the consumer tag given in [`basic_consume`](https://github.com/sozu-proxy/lapin/blob/a8ac2b2577c6c29db49fcfdf8de0a04dacccdb41/futures/src/channel.rs#L319) which means that messages aren't received by the consumer.

Code sample: https://gist.github.com/kureuil/c0914bbe0c4463acd655bfa3872b09c1

Change the consumer_tag at line 46 from `"consumer"` to `""` and it won't receive any messages.

**Comment by Keruspe** [comment]
Oh, right, I only checked the lapin-async part when trying to figure that out.
Will dig into it
