### ISSUE TITLE
How to exit heartbeat cleanly

### ISSUE THREAD

**Issue by pimeys** [sozu-proxy/lapin#114]
We have a server running on `tokio-threadpool`, where we keep all the connections in thread local variables. With Kafka and Aerospike this works quite nicely, but I've been now fighting with lapin to exit the heartbeat future cleanly. Keep in mind, while using `thread_local!` I don't really have an easy ownership to a oneshot channel, so I've been banging my head against the wall for the last couple of days. Here's one try with tokio_signal:

```rust
let _hb_thread: JoinHandle<()> = {
    let heartbeat_client = client.clone();
    let control = Signal::new(SIGINT).flatten_stream().into_future();

    thread::Builder::new()
        .name("rabbitmq heartbeat".to_string())
        .spawn(move || {
            let mut core = Core::new().unwrap();

            match core.run(heartbeat_future_fn(&heartbeat_client).select2(control)) {
                Ok(_) => {
                    info!("Producer heartbeat thread exited cleanly");
                },
                Err(_) => {
                    error!("Producer heartbeat thread crashed, going down...");
                }
            }
        })
        .unwrap()
};
```

But with SIGINT, this thread keeps the app running forever and you must SIGKILL.

The other thing I tried was to create a oneshot channel in the initializer for my RabbitMQ producer, receiver in the `select2` of the heartbeat and sender in an `Option` wrapped in my struct, so I can `take` it out in `drop`, take the ownership and send the signal to kill the heartbeat thread. This caused a segmentation fault.

There is not really any nice ways to just have the connections in the service's `self` until we get `Pin` to the stable Rust, and using `Arc` for the lapin producer in the main service is not feasible due the amount of traffic we get and everybody racing the reference counter.

What we really need is a blocking way to form a connection when the thread starts, store the connection in thread local and have a producing function returning a future for the threadpool to execute. Without the heartbeat thread the system starts nicely, produces events and exits cleanly. But when you wait for a while, the producing connections will be dead due to heartbeats missing.

**Comment by Keruspe** [comment]
In the next release of lapin (which will be released soon), you will have a
handle allowing you to exit the heartbeat future.

**Comment by pimeys** [comment]
Is it already in master, I'm quite happy to test it out already :)

**Comment by Keruspe** [comment]
Yes, you can see an example in futures/src/lib.rs iirc

**Comment by pimeys** [comment]
Ok, so now I have two versions:

```rust
let channel = Client::connect(stream, &connection_options).and_then(|(client, heartbeat)| {
    tokio::spawn(heartbeat.map_err(|_| ()));

    client.create_channel()
}).wait().unwrap();

RabbitMq { channel }
```

This one initializes and sends events, but terminating the process doesn't work and I must kill it.


```rust
let channel = Client::connect(stream, &connection_options).and_then(|(client, heartbeat)| {
    client.create_channel()
}).wait().unwrap();

RabbitMq { channel }
```

This works the same as before and I can terminate the program cleanly, but I'm missing the heartbeats and the connection is dead after 60 seconds.

**Comment by pimeys** [comment]
I think my best bet is to just SIGSEGV in the Drop for now, at least the program exits but it's not beautiful.

**Comment by kureuil** [comment]
You need to create a Handle for your heartbeat in order to stop it. Documentation for Client::connect includes an example of how to do it.

**Comment by pimeys** [comment]
Ok, so if I do this:

```rust
let (channel, handle) =
    Client::connect(stream, &connection_options).and_then(|(client, mut heartbeat)| {
        let handle = heartbeat.handle().unwrap();

        tokio::spawn(heartbeat.map_err(|_| ()));

        client.create_channel().map(|channel| (channel, handle))
    }).wait().unwrap();

RabbitMq { channel, handle: Some(handle) }
```

And then:

```rust
impl Drop for RabbitMq {
    fn drop(&mut self) {
        self.handle.take().unwrap().stop();
    }
}
```

Drop is executed, but the program hangs forever...

**Comment by pimeys** [comment]
Ok, I kind of solved this, it's hacky but can do for now. In the producer:

```rust
let stream = TcpStream::connect(&address).wait().unwrap();

let (client, mut heartbeat) =
    Client::connect(stream, &connection_options).wait().unwrap();

let handle = heartbeat.handle().unwrap();

let signal = Signal::new(SIGINT).flatten_stream().into_future().and_then(|_| {
    handle.stop();
    Ok(())
});

tokio::spawn(signal.map_err(|_| ()));
tokio::spawn(heartbeat.map_err(|_| ()));

let channel = client.create_channel().wait().unwrap();

RabbitMq { channel }
```

And then, what is important, in the main you must catch the signals with `tokio-signal` crate, otherwise it will not work.

You could probably even skip taking the handle and just `select2` with the future.
