### ISSUE TITLE
How to use the channel.basic_publish to send a batch of data?

### ISSUE THREAD

**Issue by lydia-gu** [sozu-proxy/lapin#115]
Hi there,

I am new to Rust and lapin. Now I am investigating the `lapin-futures`.
Say if I want to send 1000 messages through `channel.basic_publish` inside 
```rust
channel
.queue_declare(...)
.and_then(...
```

What should be the proper approach? Thanks!

**Comment by Keruspe** [comment]
Hi,

Are all those messages sent to the same queue? Do they all contain the same data?
If not, in which form do you have the queues/data to be sent?

**Comment by lydia-gu** [comment]
Hi Keruspe,

Thanks for your response.
1. All messages are sent to the same queue currently;
2. They contain different data;
3. These data are JSON format string, which are going to be sent one after one.

**Comment by Keruspe** [comment]
Assuming messages is a `Vec<String>ˋ containing your payloads, you can do something like
ˋ`ˋ
futures::stream::iter_ok(messages.iter()).for_each(|message| channel.basic_publish(...))

ˋ`ˋ

**Comment by lydia-gu** [comment]
Awesome, Keruspe.
After checking futures & futures-await docs now I can reproduce your solution.
Thank you for your kind guidance.
