### ISSUE TITLE
Release 0.12.0

### ISSUE THREAD

**Issue by Keruspe** [sozu-proxy/lapin#117]
I think all of the major outstanding bugs have been fixed

@kureuil @whitfin @jeffparsons you either contributed or were affected by bugs that should be fixed in current master. Can you give it a try and see if you notice anything that could block the release?

**Comment by whitfin** [comment]
I'll verify the issues I've seen, but FWIW I would count https://github.com/sozu-proxy/lapin/issues/113 as a blocker (since it's something I personally need, so I'm biased :D) until we figure out a way to avoid the 100% CPU.

**Comment by Keruspe** [comment]
#113 has been fixed without the 100% CPU thing, normally!

**Comment by whitfin** [comment]
In that case, it all looks good to me! Woohoo, Tokio Reform \o/

**Comment by kureuil** [comment]
Everything seems to be fine on my end, feel free to publish it :+1: 

Just a small note that should maybe be added to the documentation (or even changed ?) is that the new heartbeat task is using tokio-timer 0.2 which means that users either have to use the tokio runtime or launch a tokio-timer themselves to use it.

**Comment by jeffparsons** [comment]
I don't actually have any active projects using Lapin at the moment, so I
don't have anything to add other than a vague sense of enthusiasm. 😎
