### ISSUE TITLE
runs only with `RUST_LOG=lapin_futures=trace`

### ISSUE THREAD

**Issue by legokichi** [sozu-proxy/lapin#123]
"lapin-futures" = "0.11.1"

I found a lapin code that works only when `RUST_LOG=lapin_futures=trace`.

I was trying to wrap basic_get in future, e.g.

```rust
future::poll_fn(move || {
    let poll = ch2.basic_get(&queue_name, &Default::default()).poll();
    println!("{:?}", poll);
    if let Ok(_) = poll {
        // has value
        poll
    }else{
        // empty...
        Ok(Async::NotReady)
    }
})
```

but this code is stopped polling when run after `Ok(Async::NotReady)`.

here is the full code and logs - https://github.com/legokichi/rust-sandbox/tree/master/lapin-sandbox

my environment

```console
$ cat /etc/lsb-release   
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS
$ uname -a
Linux foo 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ docker --version
Docker version 17.12.1-ce, build 7390fc6
```

**Comment by Keruspe** [comment]
Btw, in your example, when hitting the Async::NotReady, tokio doesn't now when it should poll again your future, that's why it never gets polled.
You can add a task::current().notify() just before, but then you'll end up with a busy loop.

Did you give loop_fn a look?

**Comment by legokichi** [comment]
still  I don't understand why poll_fn did not work but loop_fn works fine.

```rust
future::loop_fn(ch2, move |ch2| {
    ch2.basic_get(&queue_name, &Default::default()).then(|res|{
        println!("{:?}", res);
        if let Ok(o) = res {
            // has value
            Ok(future::Loop::Break(o))
        }else{
            // empty...
            Ok(future::Loop::Continue(ch2))
        }
    })
})
```

Thank you.
