### ISSUE TITLE
Enable multiple acks in basic_ack

### ISSUE THREAD

**Issue by whitfin** [sozu-proxy/lapin#124]
It appears that `multiple: false` is hardcoded for `basic_ack`. Any intent on making this a provided value? I figure there must be some reason it wasn't added initially?

https://github.com/sozu-proxy/lapin/blob/81ad3dd308388c7093e2f6b24c38bd277e94ab71/futures/src/channel.rs#L402-L408

**Comment by Keruspe** [comment]
Sure, feel free to add this to the api (I guess it makes sense to add it to
nack too if you do)
