### ISSUE TITLE
Heartbeat blocks all consumers from continuing in 0.12

### ISSUE THREAD

**Issue by whitfin** [sozu-proxy/lapin#125]
```
MeterSnapshot { count: 414665, rates: [390.8100698087718, 730.5750441311204, 963.6300314729459], mean: 813.0564690986009 }
name: message_count labels: None
MeterSnapshot { count: 420872, rates: [394.6336229561739, 715.0688686739221, 954.5356931002789], mean: 801.6491752048053 }
name: message_count labels: None
MeterSnapshot { count: 425793, rates: [379.84412870857903, 696.1875593463596, 944.1788324173962], mean: 788.4941713438777 }
name: message_count labels: None
MeterSnapshot { count: 431172, rates: [374.9080306879829, 679.7197843340775, 934.5018666347837], mean: 776.8754486373127 }
name: message_count labels: None
MeterSnapshot { count: 436343, rates: [368.5097618284864, 663.3929785381047, 924.7543420213268], mean: 765.5033310586701 }
DEBUG 2018-06-16T19:19:38Z: lapin_futures::client: poll heartbeat
DEBUG 2018-06-16T19:19:38Z: lapin_futures::client: Sending heartbeat
name: message_count labels: None
MeterSnapshot { count: 439761, rates: [334.91339771824613, 642.0454100051794, 913.2244909211752], mean: 751.7178407188896 }
name: message_count labels: None
MeterSnapshot { count: 439761, rates: [260.830816404075, 610.7324858625518, 898.1302177517547], mean: 732.9250308062573 }
name: message_count labels: None
MeterSnapshot { count: 439761, rates: [203.13524406464748, 580.9467110509256, 883.285430973444], mean: 715.0489367894609 }
name: message_count labels: None
MeterSnapshot { count: 439761, rates: [158.20188714694842, 552.6136056185545, 868.6860069389069], mean: 698.0240798297584 }
name: message_count labels: None
MeterSnapshot { count: 439761, rates: [123.20775359341746, 525.6623220438021, 854.3278901587024], mean: 681.7910729352898 }
name: message_count labels: None
MeterSnapshot { count: 439761, rates: [95.95429497902224, 500.0254680794349, 840.2070921747342], mean: 666.2959256376611 }
```

These are my logs, showing 15 second windows of the rates. You can see that the moment the heartbeat sends, the count stops increasing and no messages are received. I confirmed this by looking in the RabbitMQ UI, and seeing a delivery rate of 0/s.

**Comment by Keruspe** [comment]
Fwiw I have a rework of consumers in progress locally, hopfully that’ll fix
this

**Comment by whitfin** [comment]
@Keruspe ok; I can reproduce it pretty much consistently so I can verify whenever you want. In the meantime, I'll try track down the issue (I also confirmed it still happens in current master).

**Comment by whitfin** [comment]
This appears to be trace logs immediately before the consumer halts:

```
DEBUG 2018-06-17T03:13:45Z: lapin_futures::client: poll heartbeat
DEBUG 2018-06-17T03:13:45Z: lapin_futures::client: Sending heartbeat
TRACE 2018-06-17T03:13:45Z: lapin_futures::transport: transport poll
TRACE 2018-06-17T03:13:45Z: lapin_futures::transport: transport poll_recv; status=NotReady
TRACE 2018-06-17T03:13:45Z: lapin_futures::transport: transport poll_send; frame=Heartbeat(0)
TRACE 2018-06-17T03:13:45Z: lapin_futures::transport: transport start_send; frame=Heartbeat(0)
TRACE 2018-06-17T03:13:45Z: lapin_futures::transport: encoder; frame=Heartbeat(0)
TRACE 2018-06-17T03:13:45Z: lapin_futures::transport: encoder; sz=8 length=0 extend=8
TRACE 2018-06-17T03:13:45Z: lapin_futures::transport: encoder; frame_size=8
TRACE 2018-06-17T03:13:45Z: lapin_futures::transport: transport poll_send; status=Ready
TRACE 2018-06-17T03:13:45Z: lapin_futures::transport: transport poll_complete
```

**Comment by whitfin** [comment]
It appears to be exactly that; a heartbeat will block the consumers - but when the next heartbeat sends, it unblocks and consumers start again. Very strange :p

**Comment by Keruspe** [comment]
I might have an idea.
Let me polish what I have locally (that is finally working), that should
fix it

**Comment by Keruspe** [comment]
Can you retry with current master?

**Comment by whitfin** [comment]
@Keruspe this does appear to be fixed at a glance, nice! 

Is there any chance this can be tagged soon-ish as maybe a 0.12.x? If not, could you point me to the specific fix for the heartbeat issue so I can maybe pull it on top of the release version?

**Comment by Keruspe** [comment]
And it’s still the same issue ? Heartbeat « pauses » the consumers, and the next one « resumes » those ?

**Comment by whitfin** [comment]
@Keruspe exactly that - in the log above you can see the logs from the heartbeat, and then the count stays the same for another minute (these logs are every 15s) until my next heartbeat, and then it starts to increment again.

It's not every single heartbeat that stops it, but it's most of them. I'd say maybe 90% of the time the heartbeat would pause the consumers.

**Comment by Keruspe** [comment]
Can you try to get logs with the trace log level?

**Comment by whitfin** [comment]
@Keruspe I posted them a [little further up](https://github.com/sozu-proxy/lapin/issues/125#issuecomment-397851676) - that's the entirety of the logs on trace when it happens.

**Comment by Keruspe** [comment]
Oh right, sorry.
I’ll add some more logs I guess

**Comment by Keruspe** [comment]
When the consumer pauses, are there messages in the queue?

**Comment by Keruspe** [comment]
The only case where I am able to reproduce is if there are 0 message in the queue when the heartbeat is sent, then some messages get queued. In this case the new messages are only consumed when the next heartbeat comes.

**Comment by Keruspe** [comment]
Trying to reproduce this, I had a consumer eating 5k/s and a producer publishing 20k/s and it helped me find another bug for which I have a fix locally

**Comment by whitfin** [comment]
That sounds like the same case; sorry I thought you meant when the heartbeat hits does it causes a backlog.

To clarify; there are no queues messages (the delivery keeps up), then when the heartbeat hits it backs up and doesn’t deliver until the next heartbeat.

**Comment by Keruspe** [comment]
Should be fixed in master, please reopen if it's not for you
