### ISSUE TITLE
Example in README.md for Creating a Consumer Doesn't Actually ACK messages

### ISSUE THREAD

**Issue by d0nutptr** [sozu-proxy/lapin#130]
The example on how to create a consumer in the `README.md` file doesn't appear to ACK messages as they're processed. I still don't really understand `tokio` all that much but I believe you have to return the `ack` future to have them processed.

Example of corrected code:
```
stream.for_each(move |message| {
    debug!("got message: {:?}", message);
    info!("decoded message: {:?}", std::str::from_utf8(&message.data).unwrap());
    ch.basic_ack(message.delivery_tag)
    // remove Ok(())
})
```

Sorry for the lame issue! I just wanted to make sure this was documented in case anyone is confused like I was why my messages weren't being ack'd :)

**Comment by seunlanlege** [comment]
I actually think the examples could be significantly made better.

**Comment by Keruspe** [comment]
Fixed, thanks
