### ISSUE TITLE
Moving to 'impl' return types is deadly

### ISSUE THREAD

**Issue by hedgar2017** [sozu-proxy/lapin#150]
Since the version 0.13 it is nearly(?) impossible to store the future types of this crate in structures.
If it is a simple deducible 'impl', then I can write a 'Box' type for it. But I have encountered a nested (!!!) impl-type, and it is absolutely impossible to store such a type in a struct.
Here is it: [Client::connect](https://docs.rs/lapin-futures/0.14.1/lapin_futures/client/struct.Client.html#method.connect)

I had to move back to the version 0.12 to able to store the crate's futures in state machines.
Is this crate suitable only for using in combinators or am I missing something?

**Comment by Keruspe** [comment]
Why would you want to store the Heartbeat?

The method connect gives you a tuple containing the client and a Heartbeat object (which is the one you're having difficulties to store).

You're supposed to just spawn the Heartbeat in an executor. What you might want to store is the HeartbeatHandle that you can get by calling .handle() on your Heartbeat.

**Comment by Keruspe** [comment]
Can you provide a minimal code sample?

**Comment by hedgar2017** [comment]
This is a sample of using `state_machine_futures`:

```
type ConnectingRabbitmqFuture =
    Timeout<Box<Future<Item = (Client<TcpStream>, Heartbeat), Error = io::Error> + Send>>;
type CreatingChannelFuture =
    Timeout<Box<Future<Item = Channel<TcpStream>, Error = io::Error> + Send>>;
type PublishingFuture = Timeout<Box<Future<Item = Option<u64>, Error = io::Error> + Send>>;

#[derive(StateMachineFuture)]
#[state_machine_future(context = "Context")]
#[doc(hidden)]
pub enum RabbitmqStateMachine {
    #[state_machine_future(start, transitions(ConnectingTcp, Publishing))]
    Start,

    #[state_machine_future(transitions(ConnectingRabbitmq))]
    ConnectingTcp { future: Timeout<tcp::ConnectFuture> },

    #[state_machine_future(transitions(CreatingChannel))]
    ConnectingRabbitmq { future: ConnectingRabbitmqFuture },

    #[state_machine_future(transitions(Publishing))]
    CreatingChannel { future: CreatingChannelFuture },

    #[state_machine_future(transitions(ConnectingTcp, Ready, Error))]
    Publishing {
        future: PublishingFuture,
        channel: Option<Channel<TcpStream>>,
    },

    #[state_machine_future(ready)]
    Ready(()),

    #[state_machine_future(error)]
    Error(RabbitmqError),
}
```

It uses `lapin_futures 0.12`. Starting from 0.13 I cannot store the type `ConnectingRabbitmqFuture`, as I contains an inner `impl` which cannot be turned to Box by the compiler.
Or I'm just bad at Rust yet and I don't know something.

**Comment by Keruspe** [comment]
Can you maybe make a github repository using state_machine_futures and lapin 0.12 just connecting to the amqp server and creating a queue or something like that? This way I can try and update it to the latest lapin version

**Comment by hedgar2017** [comment]
Sure. I'll do it later today.

**Comment by hedgar2017** [comment]
I have created a minimal example and invited you.

**Comment by Keruspe** [comment]
I just pushed two branches, with two different solutions:

- the updates branch just updates lapin to the latest version
- the tls branch switches to lapin-futures-rustls, which brings tls support as a bonus
