### ISSUE TITLE
Heartbeat blocking consumer on lapin-futures 0.15.0

### ISSUE THREAD

**Issue by jgrund** [sozu-proxy/lapin#152]
I am hitting an issue where spawning the heartbeat on another task appears to block a basic_consume stream from handling messages ~%80 of the time.

If I skip spawning the heartbeat on another task, the consume stream gets messages every time.

Likewise, if I stop the heartbeat, the consume stream gets messages every time.

**Comment by Keruspe** [comment]
Hi,

Could you provide a simple reproducer so that I can give a try at debugging this?

**Comment by Keruspe** [comment]
Which executor are you using?

**Comment by jgrund** [comment]
I am using the default executor in tokio: https://docs.rs/tokio-threadpool/0.1/tokio_threadpool/struct.ThreadPool.html

**Comment by Texlo-Dev** [comment]
@jgrund Hi,
I am encountering a similar issue, where not all of my messages are being consumed appropriately. I've tried disabling the heartbeat, the issue still persists.

**Comment by Keruspe** [comment]
Could you try with 0.19.0?
I'm releasing a few alphas until it's properly ready but things should already be better
