### ISSUE TITLE
Integrate lapin-futures with actix

### ISSUE THREAD

**Issue by ivan-ochc** [sozu-proxy/lapin#153]
Hi! I'm trying to integrate **lapin-futures** with **actix-web** to simultaneously handle subscription to rabbitmq queue, database connection and REST API to work with database.
I've succeeded only with such approach: start this [code](https://github.com/sozu-proxy/lapin/blob/master/futures/README.md) in the new thread with `thread::spawn`. If start this code without `thread::spawn` It ignores actix-web at all: only **lapin-futures** starts.
Is it possible to use **lapin-futures** in scope of **actix actors**?  

My knowlege of actix, rabbitmq and rust in general is very basic therefore it's very possible that I miss something.

**Comment by thedodd** [comment]
@ivan-ochc if you just need to make an async call from withing an actix-web handler, you should be able to do that without any problem. The new will just use the executor of the parent future. If you need to spawn a new task — IE, a futures 0.1 `Future<Item=(), Error=()>` — then you should be able to just do `tokio::spawn(new_task)`. You can definitely use an actor ... but you shouldn't have to if it is just a simple network call.

However, if you have a long-running connection, like a RabbitMQ consumer connection, where you need to perform additional work when a message is received; that is the perfect use for an actor.

A final note, outside of the actix context, this would just be a "task" as mentioned above. The sort of thing you would spawn on the tokio runtime from within your `tokio::run` future. You don't need the result of the task when you spawn it, as it should be self-contained and probably spawns other tasks or does other async work on its own.

**Comment by ivan-ochc** [comment]
@thedodd, thanks for your answer. I've tried `tokio::spawn(new_task)`. It works ok so far.

**Comment by Keruspe** [comment]
I think we can close this one then
