### ISSUE TITLE
Improper Licensing

### ISSUE THREAD

**Issue by aembke** [sozu-proxy/lapin#154]
In a recent dependency audit we found that lapin-async uses [sasl](https://gitlab.com/lumi/sasl-rs), which uses LGPLv3. I'm not an expert on this but I think that means lapin must then also use LGPLv3 as it is statically linked to Sasl and therefore a derivative work. 

I'm not sure if you'd like to handle this by removing that dependency or adjusting the license of lapin, but if it's the former we have some internal code that can perform plain AMQP auth without the sasl dependency. All in all it's only a few lines of code, but we're using an older version of lapin so unfortunately it's not as simple for us to just submit a PR as our versions have drifted apart quite a bit.

**Comment by Keruspe** [comment]
Thanks for the report, I’ll give it a look!

We mentioned removing it in the past so we might as well do that now.

Do you want to give it a try ?

**Comment by aembke** [comment]
Yeah sure I'll submit a PR with an adapted version of the changes we made, but it'll likely have to wait until tomorrow if that works for you.

**Comment by Keruspe** [comment]
Just fixed it actually, was pretty trivial to replace
