### ISSUE TITLE
Channel basic_nack with delivery tag "0" (basic_recover) with prefetched messages

### ISSUE THREAD

**Issue by serejkaaa512** [sozu-proxy/lapin#155]
Starting Consumer with Qos options setted prefetch count > 1, we receive message stream.  If one will send basic_nack with delivery tag "0" or basic recover on the channel used, by documentation - "If the multiple field is 1, and  delivery tag is zero, this indicates rejection of  outstanding messages". So all messages that were prefetched became not valid, acking or nackacking them will result to raise channel exception and close it, because delivery tag is not valid anymore.
There is a proposal to clear prefetched queue when one of this events appear.

**Comment by Keruspe** [comment]
Thanks for the report!

So, let me sum this up, to make sure we're on the same page. Two similar problems here:

- basic_nack with multiple = true and delivery_tag = 0 should drop all messages that have been prefetched from the stream
- basic_recover should also drop all messages that have been prefetched from the stream

Is there something similar for basic_ack?
Could you point me to the right place in the documentation?

**Comment by serejkaaa512** [comment]
For basic ack here what i found in documentation: "If the multiple field is 1, and delivery tag is zero, this indicates acknowledgement of outstanding messages." So suppose that we need also drop all prefetched messages in this case.

**Comment by Keruspe** [comment]
@michaelklishin Could you maybe clarify what we are supposed to do there?

**Comment by Keruspe** [comment]
This should be fixed by 40294dbde464a63199e77efdfa33fad120c84570 and f1e798b77d9d0f4804ab6e616697eb5f73088486

This also led me to fix 827966fffe98287502b52f4b788138be061848b6

I'll make a new release shortly
