### ISSUE TITLE
strange behavior of consumer stream

### ISSUE THREAD

**Issue by serejkaaa512** [sozu-proxy/lapin#159]
I've faced with strange behavior of consumer.

I've got web app with single event loop (running with tokio_core::reactor::Core). I am spawning consumer with `core.handle().spawn(consumer)` and it is running all the way, application lives.

My consumer looks like this:
```rust
let futures = consumer_and_chans.into_iter().map(move |(stream, channel)| {
        stream
            .for_each(move |message| {
                let delivery_tag = message.delivery_tag;
                let fetcher_future = fetcher.handle_message(message.data);
                let timeout = Duration::from_secs(timeout);
                Timeout::new(fetcher_future, timeout)
                    .then(move |res| match res {
                        Ok(_) => Either::A(channel.basic_ack(delivery_tag, false),
                        Err(e) => Either::B(basic_nack(0, true, true)                        
                    })
                    .then(move |res| {
                        Ok(())
                    })
            })
```

When i am handling web request, i use basic publish to send message to other (not the one being consumed) queue.

In that moment of time something strange happens with consumer, it stops to poll its stream.

It happens not everytime, but, i think, it happens when i am publishing message in the period of time after message was received from stream but before basic ack was sent to rabbit.

Log can be found [here](https://gist.github.com/serejkaaa512/a6e924cf1330c33f5bc2f1778897cd28).
I have marked where to pay attention with comments.

**Comment by serejkaaa512** [comment]
Having analyzed code and reading tokio [docs](https://tokio.rs/docs/internals/runtime-model/), i have a couple of remarks.
1. Consumer poll fn is returning Ok(Async::NotReady), if delivery is not ready.  Due to tokio documentation of BadTask from AsyncNotReady section: `..During this transition, no resource has returned NotReady. When the task itself returns NotReady, it has violated the contract as the task will not be notified in the future.` - i don't clearly understand if this is our case, but it looks like. 
2. Another thing in the docs - `If multiple tasks have expressed interest in a resource, only the last task to have done so will be notified. Resources are intended to be used from a single task only.` Maybe both calling basic_consume and basic_publish use one resource and only last one is being notified?

Maybe we can call `task::current().notify();` before `Ok(Async::NotReady)`? It is dumm suggestion and can cause high CPU utilization, but think it's better than stop polling consumer stream.

**Comment by serejkaaa512** [comment]
I have examined logs a little bit more and have one more question. As i understand the code, we are saving consumer task on first poll call and when transport handles AMQP Body frame we call this task notify. But according to logs consumer poll function calling repeats without any message received from transport (it receives `transport poll_recv; status=NotReady`), and it returns `Async::NotReady`, so due to the docs, polling by event loop must be stopped until this task will by notified. @Keruspe can you, please, clarify where am i wrong?

**Comment by serejkaaa512** [comment]
Tried to fix this issue, by moving all tasks notification to transport poll. At least on each heartbeat all consumers will be notified and will try to poll the stream. Sent [Pr](https://github.com/sozu-proxy/lapin/pull/160). Any remarks are welcome!

**Comment by serejkaaa512** [comment]
I spent some more time exploring this issue. And this is what i found:
1. In my case i have 3 consumers and one publisher, plus heartbeat stream. They all use one RabbitMQ connection (TCPStream).
2. As written in (docs)[https://tokio.rs/docs/internals/net/]: `Network resources are types, such as TcpListener and TcpStream, that are composed of the network handle and a reference to the driver that is powering the resource.` and `Calls to [Reactor::turn] uses [mio::Poll::poll] to get operating system events for registered network resources. It then notifies the registered tasks for each network resource using the [task system]`. So i have reactor that use registered network resource to get operating system events.
3. Continue reading the docs - `Note that there is only a single task field per resource. The implications are that a resource can only be used from a single task at a time. ... Notifying the task results in the task getting scheduled on its executor. `
I think this is what happening - One resource (TCP Stream) is being used by 5 different tasks, but, by the docs, can be used only from a single task, so only one gets notified. Other tasks are simply not scheduled on executor.
My workaround: to save consumers tasks somewhere near the resource and when it's get updated by operating system events to notify all tasks manually. In pull-request i propose to save it in transport and, as by-design, heartbeat must be always called, manually notify all consumers, when it's happening. 
Think this issue may be related to #133.

**Comment by Keruspe** [comment]
Are you still using tokio-core or are you using tokio?
I have some rework that will land by the end of the month that might or might not fix this.
Wrt the NotReady usages, we always notify before doing that for tasks that will need to be polled again so we should be safe wrt that

**Comment by Keruspe** [comment]
Can you try with 0.19.0-alpha1?

**Comment by Keruspe** [comment]
Care to try with 0.19.0 beta1?

**Comment by Keruspe** [comment]
Should be fixed by now.

Please reopen with some code sample if you manage to still reproduce this
