### ISSUE TITLE
pre-consume/fetch all messages on a queue

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [sozu-proxy/lapin#162]
Hi,

I have build a library [amqp_worker](https://crates.io/crates/amqp_worker) on top of lapin futures.
And it become very simple to build workers like this one: https://github.com/FTV-Subtil/rs_http_worker

I have an issue with the library (maybe just a small missing configuration or maybe a misunderstood on my side).
When worker start to listen on the queue, it will pre-consume all messages in the queue. So if I start a second worker, no messages are presents. So I can scale my workers on the same queue...

I have tried to add an BasicQosOptions with `prefetch_count: 2`, but it changes nothing.

Do you have any idea how to solve that ?
Is it a consume configuration issue or a problem using the stream consumption ?

Thanks for your help !

**Comment by Keruspe** [comment]
I’m not sure about this, will give you a closer look after the next release I’m working on

**Comment by MarcAntoine-Arnaud** [comment]
Thanks, do you have something who I can test ? Or some ideas to contribute on it ?

**Comment by Keruspe** [comment]
You could start by trying to do something similar with another language and client, like bunny in ruby and see how it behaves to figure out if it’s a problem in lapin or in the way to do things

**Comment by MarcAntoine-Arnaud** [comment]
I have already a [python worker](https://github.com/FTV-Subtil/py_ftp_worker/) who do the same job (and accept same message, we wanna to replace python by Rust ! ).
And it's still in queue normally as expected.
So I think it's a lapin related issue...

**Comment by Keruspe** [comment]
Ok ! Well, let me finish my current work on lapin which should land by the end of the month which will clean things up, and then it'll be easier to debug this :)

**Comment by MarcAntoine-Arnaud** [comment]
Okay I'll take a look into it deeper because I can't wait until April. I hope to release it this week...

**Comment by Keruspe** [comment]
Hmm, if you go the the management interface, in the channel list, what do the channel created using python and the one created using rust look like? Especially the prefetch column

**Comment by Keruspe** [comment]
I might have the answer there if you're willing to try a patch

**Comment by Keruspe** [comment]
Could you try the quick fix from https://github.com/sozu-proxy/lapin/tree/qos ?

**Comment by MarcAntoine-Arnaud** [comment]
Yes I can try tomorrow of course.
In the RabbitMQ management UI messages are all in "unacked" side ...
I'll tell you tomorrow for the patch.

**Comment by MarcAntoine-Arnaud** [comment]
Hoo I see you've patched the async version.
I use the Future not async.
I'll try to apply the patch on Future.
(many thanks for your reactivity !!!)

**Comment by Keruspe** [comment]
The futures version uses the async one under the hood.
Anyways, the patch was wrong, I actually found the mistake and fixed it in master.
It *did* work, but we didn't wait for it to work before continuing, so we started consuming before the qos was applied

**Comment by MarcAntoine-Arnaud** [comment]
I Marc-Antoine,
After testing the patch I understood the return function is a future, and I missed to wait the result ...
So even with the release 1.17 it's works perfectly.

Sorry for that.
Maybe in the future we can add more example here for example:
https://docs.rs/lapin-futures/0.18.0/lapin_futures/channel/struct.Channel.html#method.basic_qos
to show who to use the function:
```rust
channel.basic_qos(BasicQosOptions{
  prefetch_size: 0,
  prefetch_count: 1,
  global: true,
}).wait();
```
