### ISSUE TITLE
Weird behavior with consumers

### ISSUE THREAD

**Issue by tyrylu** [sozu-proxy/lapin#165]
In one of my applications, i tried to use the lapin_futures crate with tokio-async-await. Everything seems to work, except consuming from a queue.
The relevant code portion is as follows:
```
let mut consumer = await!(channel.basic_consume(
        &tasks_queue,
        "tasks_consumer",
        BasicConsumeOptions::default(),
        FieldTable::new()
    ))?;
    info!("Starting tasks consumption...");
        while let Some(msg) = await!(consumer.next()) {
        let msg = msg?;
        let task: BackgroundTask = serde_json::from_slice(&msg.data)?;
        task.execute()?;
        await!(channel.basic_ack(msg.delivery_tag, false))?;
    }
```
And the relevant trace log portion (after sending the consume request) is in this gist:
https://gist.github.com/tyrylu/e2ce651697fea99db7402bbc0cf84b17
Note that the consumer_ok and the deliver messages came in a single TCP packet, so if this might be the cause...
Creating a separate channel for the consumer doesn't help much, that results in an error that the channel is not connected, or something like that.

**Comment by tyrylu** [comment]
What's even weirder, even basic_get ends in an infinite wait...

**Comment by tyrylu** [comment]
Another find, if the consumer is created on the first channel, it works. If not, on Linux, it gets stuck, under Windows, the consumer creation ends up with a Not connected error.

**Comment by tyrylu** [comment]
Alright, a correction, it works sometimes, but not always. But yes, using the first channel helps a lot.

**Comment by tyrylu** [comment]
Okay, the error is not directly related to lapin_futures, it's a bug in lapin_async.

**Comment by Keruspe** [comment]
I have some rework of lapin-async that fixed a few bugs wrt consumers handling amongst other things. I’m currently polishing things and will probably publish a beta next week if you want to give it a try

**Comment by Keruspe** [comment]
Can you try with 0.19.0-alpha1?

**Comment by tyrylu** [comment]
Works with the alpha, thanks.
