### ISSUE TITLE
Consumer broken when two queues are declared on a channel

### ISSUE THREAD

**Issue by tyrylu** [sozu-proxy/lapin#167]
When you use a channel for two queue declarations and then you want to consume from one of them, the for in the lapin_async basic.deliver handling may set the connection state such that the next messages are assumed to come for the second queue, but that one doesn't have a consumer, so the messages are dropped.
If this behavior is desired, it should at least be pointed out in the docs. By the way, that's the root cause for https://github.com/sozu-proxy/lapin/issues/165

**Comment by Keruspe** [comment]
Yeah, I noticed that with my current rework, it’s fixed locally, just not
yet in a publishable state, but beta is coming soon

**Comment by tyrylu** [comment]
I'll definitely will have a look, probably do a quick test (i'm looking forward to removing the ugly hack which fixes this behavior for me for now).

**Comment by Keruspe** [comment]
Can you try with 0.19.0-alpha1?

**Comment by tyrylu** [comment]
Seems to work okay with the alpha.
