### ISSUE TITLE
Error after publishing a message

### ISSUE THREAD

**Issue by tyrylu** [sozu-proxy/lapin#178]
Hello.
When having a lapin_futures channel and the following sequence of commands (uses the await! macro from the tokio-async-await crate):
```
await!(channel.basic_publish(exchange, "", body_bytes, BasicPublishOptions::default(), BasicProperties::default()))?;
await!(channel.close(0, "Normal shutdown"))?;
```
The client sends the basic.publish command and immediately the close command, which results in a hard channel error:
```
2019-06-12 12:17:33.575 [error] <0.8870.0> Error on AMQP connection <0.8870.0> (127.0.0.1:35482 -> 127.0.0.1:5672, vhost
: '/', user: 'admin', state: running), channel 1:
 operation basic.publish caused a connection exception unexpected_frame: "expected content header for class 60, got non
content header frame instead"
```
Happens with 0.19 RC1, began happening somewhere around the 0.19 betas, but i haven't identified the point (because of the API changes a bisect would not be as straightforward as it should). But thank for the changes, by the way, they helped.

**Comment by tyrylu** [comment]
And to add, awaiting a tokio_timer Delay for a few tens of milliseconds (just to be sure) fixes the ordering issue.

**Comment by Keruspe** [comment]
Right, this probably comes from the frames priority stuff.
I probably know what’s going on, will fix today

**Comment by Keruspe** [comment]
Fix is now in rc2
