### ISSUE TITLE
Connection error reporting

### ISSUE THREAD

**Issue by xabufr** [sozu-proxy/lapin#181]
Hi !
I've recently updated lapin to 0.21.2, and the new API looks nice !
But while with older one I could use heartbeats to detect some connection errors, this part of the API is hidden in lapin-future.
I can't find a good way to handle connection errors and do appropriate work (reconnection, abort, etc...) with future api.
For instance when I kill the rabbitmq server, I got a log line `ERROR [lapin_async::channel] Connection closed on channel 0 by 0:0 => Hard(CONNECTIONFORCED) => CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'`, but the error is not reported in the future.
It would be nice to have some API to handle these errors, or at least the connection state.

EDIT: It seems the future API doesn't report error for initial connection, i.e with `Client::connect_uri`

**Comment by Keruspe** [comment]
Wrt the initial connection error, the connection state switches to Error but the calls return a success for now (the next call returns an error), indeed.
I have some ideas on how to fix this, but haven't found the time to try those yet.

Wrt connection error handling, what do you fink of something like `connection.on_error(|| { /*your code here*/ })`?

**Comment by xabufr** [comment]
For connection error handling I think it would be sufficient for my use case, right now I don't see another more elegant solution.

**Comment by Keruspe** [comment]
0.21.3 should be better in these regards :)

**Comment by xabufr** [comment]
Thank you !

**Comment by ginkcode** [comment]
Can you suggest any way to run async code here.
I want to send back a message by tokio `mpsc::channel`. But async block is not allowed here at `connection.on_error()`.

If I start a runtime to run `block_on`, will hit another error because `#[tokio::main]` created a runtime already.
```
thread 'tokio-runtime-worker' panicked at 'Cannot start a runtime from within a runtime.
```
