### ISSUE TITLE
Authentication with lapin v0.20.0

### ISSUE THREAD

**Issue by fourlightyears** [sozu-proxy/lapin#184]
I was able to connect with a specific username/password (rather than guest/guest) using the Credentials parameter of Client::connect() by say, passing in Credentials::new("bunnyuser", "carrotpasswd"). in v0.19.0.

But in v0.20.0. the Credentials parameter no longer seems to exist.  I can't find how to set the username in the examples or tests or documentation. I am guessing that it would be something like setting something within the ConnectionProperties parameter, but can't quite zero in on what to do. 

Would you be able to advise on this? Thanks.

I did try the amqp://username:password@localhost:xxxx trick but the rabbitmq log showed a failure with a wrong default login attempt (using the username 'guest' rather than the user I specified).

**Comment by Keruspe** [comment]
username and password need to be url escaped when they contain "special" chars.

It works fine here passing creds in the uri

**Comment by Keruspe** [comment]
Can you try "amqp://username:password@localhost:xxxx".parse<AMQPUri>() and print the output to see if it's the expected one?

**Comment by fourlightyears** [comment]
Thanks for the quick response.

The username contains only lowercase letters and the password has letters
and numbers only. I ran into some unrelated system trouble today, so
couldn't finish trying your parse() suggestion which I was attempting
nevertheless. I will check tomorrow.

**Comment by fourlightyears** [comment]
It's working for me today. It could have been my mistake; I was modifying the source file in  lapin/futures/tests/ and executing 'cargo test'. I had different versions of lapin cloned in different folders, and I could have been in the wrong folder.

Maybe it's worth mentioning in the document that putting the username and password in the ampq URI is 'the way' (if indeed it is) to login to the RabbitMQ server?

Apart from that, I think this issue can be closed.
