### ISSUE TITLE
Verifying Publisher confirms

### ISSUE THREAD

**Issue by fourlightyears** [sozu-proxy/lapin#186]
I have been trying to port code written to use a previous lapin version to make it use v0.20.0, but I'm stuck with a compilation error.

It's when calling basic_publish() and applying and_then() on it.

The documentation here: https://docs.rs/lapin-futures/0.20.0/lapin_futures/struct.Channel.html#method.basic_publish says:

> 
> pub fn basic_publish(
>     &self, 
>     exchange: &str, 
>     routing_key: &str, 
>     payload: Vec<u8>, 
>     options: BasicPublishOptions, 
>     properties: BasicProperties
> ) -> ConfirmationFuture<()>
> 
> publishes a message on a queue
> 
> the future's result is:
> 
> Some(true) if we're on a confirm channel and the message was ack'd
> Some(false) if we're on a confirm channel and the message was nack'd
> None if we're not on a confirm channel

The prototype (returning ConfirmationFuture<()>) seems to imply that the parameter that gets passed to the lamda function for and_then() will be the unit type (), and not an Option<> type and indeed this is what my compiler tells me:

> 
>     |
> 259 |                                             .and_then(move |confirm| match confirm {
>     |                                                                            ------- this match expression has type `()`
> 260 |                                                 Some(ack) => {
>     |                                                 ^^^^^^^^ expected (), found enum `std::option::Option`
>     |
>     = note: expected type `()`
>                found type `std::option::Option<_>`
> 

Have you got an example of how to how to verify confirms? I couldn't find one in the test or examples folder. 

I've been only a few months into Rust, so apologies if I'm overlooking something.

**Comment by Keruspe** [comment]
Hello,

The doc seems outdated indeed, could you maybe update it and make a PR ?
The correct way now is to call wait_for_confirms which returns a list of
nacked messages.
This better matches what other clients do and follows official rabbitmq
recommendations not to wait for confirm for every message

**Comment by fourlightyears** [comment]
Thanks. I could update it (src/channel.rs), but I'm wondering how to do so in such a way that the update appears for each version (from v0.19,0 unitl v0.24.0 I believe) in docs.rs. Obviously, I could do it just for the head, but the documentation will only be correct for versions from v0.25.0 onward. 

Okay, after writing the above, I see that the lib version resides in Cargo.toml. So, if I make the change for v0.19.0 and merge it into my local copy of v0.20.0 and then merge that to the next version, and so on, assuming that docs.rs will probe the repository for the latest changeset corresponding to a Cargo.toml version, will that do?  In this case, since the documentation for wait_for_confirms() and basic_publish() hasn't changed there should hopefully be no merge conflicts, or any conflicts should be easily merge-able.

**Comment by Keruspe** [comment]
Yeah, we cannot change documentation for previous versions.
I edited the comments in 0.24.0
