### ISSUE TITLE
Timeout error not handled on stream consuming

### ISSUE THREAD

**Issue by fan-tom** [sozu-proxy/lapin#188]
After #187 has fixed lapin writes to log
```
IO error: Os { code: 60, kind: TimedOut, message: "Operation timed out" } }
[2019-07-11T14:19:42Z ERROR lapin::connection] Connection error
```
but Comsumer stream doesn't return error. Actually, Consumer never returns error

**Comment by Keruspe** [comment]
Client::on_error is called as expected though, right?

Will look at what's going on with streams

**Comment by Keruspe** [comment]
I think I know what's going on

**Comment by fan-tom** [comment]
> Client::on_error is called as expected though, right?
Unfortunately, no. I add logs and here
```
  pub(crate) fn set_error(&self) -> Result<(), Error> {
    error!("Connection error");
    self.set_state(ConnectionState::Error);
    self.channels.set_error()?;
    trace!("About calling handler error");
    self.error_handler.on_error();
    Ok(())
  }
}
```
trace is not executed

**Comment by Keruspe** [comment]
AH! I know where this one comes from.
I have a fix for this WIP, and a plan to fwd errors properly from consumer

**Comment by Keruspe** [comment]
trace should now be executed correctly with current master.

Error is not yet forwarded to stream though

**Comment by Keruspe** [comment]
Error is still not forwarded but at least the stream should be terminated now

**Comment by fan-tom** [comment]
Wonderful, you fix bugs so quiqly I never seen before anywhere, many thanks
