### ISSUE TITLE
cannot access source of latest release (0.26.x)

### ISSUE THREAD

**Issue by Dowwie** [sozu-proxy/lapin#195]
I want to adopt the latest lapin + lapin_futures in my work but cannot access its corresponding source.  :(

The latest version of lapin is 0.26.1 and yet I can't find a branch, release, nor tag of it in this github repo.  Further, the master branch is no longer consistent with objects and api of 0.26, so it cannot be used as a reference.  Would you please continue sharing release packages and at least share the latest 0.26.1 package, please?

Thanks for considering!

**Comment by Keruspe** [comment]
It’s the last commit on master branch

**Comment by Dowwie** [comment]
@Keruspe as you may understand, I had to verify with you whether a commit was a reliable source

**Comment by Keruspe** [comment]
It’s literally the message of the commit...

Haven’t pushed tags lately as I do not have my gpg key with me
