### ISSUE TITLE
where is the channel.rs source code that corresponds to QueueDeclareOptions?

### ISSUE THREAD

**Issue by Dowwie** [sozu-proxy/lapin#196]
what is the location of the source that corresponds to QueueDeclareOptions? this source seems to be derived at compile time from a data file that I do not see packaged with the crate.  https://docs.rs/lapin/0.26.2/lapin/options/struct.QueueDeclareOptions.html

**Comment by Dowwie** [comment]
found it: https://crates.io/crates/amq-protocol-codegen

I will have to use docs.rs rather than read source to understand what is going on.  thanks.

**Comment by Keruspe** [comment]
Which problem are you trying to solve? I can guide you

**Comment by Dowwie** [comment]
@Keruspe in this case, I wanted to understand what the default values were and what other options were available.  I first tried searching for an answer through code but failed because the answer was part of derived code.  Instead, I had to rely on docs.  This is fine, but as I am unfamiliar with the project wasn't aware until now.

**Comment by Keruspe** [comment]
Yeah, as most rabbitmq client, this part is generated from a json
descriptor provided by rabbitmq.
Default values are basically the default of each type.
This should probably be documented, if you want to give a shot at improving
the situation
