### ISSUE TITLE
#194 still remain

### ISSUE THREAD

**Issue by Matrix-Zhang** [sozu-proxy/lapin#197]
#194 
[lapin.tar.gz](https://github.com/sozu-proxy/lapin/files/3500819/lapin.tar.gz)

**Comment by Keruspe** [comment]
Ok, so there were two (rather similar) problems there, fixing the second one

**Comment by Keruspe** [comment]
Should be fixed in 0.26.4

**Comment by Keruspe** [comment]
Btw, while we sure can fix this in the client library (still digging to make sure I did it correctly), channels are not supposed to be used across multiple threads, it's recommended to create at least one channel per thread
