### ISSUE TITLE
MQTT Support

### ISSUE THREAD

**Issue by shekohex** [sozu-proxy/lapin#199]
Hello, can I use this with MQTT?

**Comment by Keruspe** [comment]
Hi,

MQTT is a totally different protocol. Lapin is only compatible with AMQP

**Comment by shekohex** [comment]
thank you @Keruspe

**Comment by Keruspe** [comment]
Fwiw, https://crates.io/crates/mqtt3 doesn't seem really maintained but works just fine for basic stuff

**Comment by shekohex** [comment]
yeah, but for a moment I thought that AMQP has something related to MQTT.
anyway, I'm will start working on a broker for the MQTT v3.1.1.

> off-topic: I'm using lapin in one of my projects with async/await feature, and it's awsome, thank you for that work :+1:
