### ISSUE TITLE
Client side certificate/private key

### ISSUE THREAD

**Issue by axelfaure** [sozu-proxy/lapin#200]
First of all, thank you for the work you put into this library.

I am trying to use lapin to connect a third party AMQP server. Unfortunately, I need to provide a client-side TLS authentication (pre-shared PKCS12 certificate).

Is there any way to do that using lapin (either by letting lapin handle it or by handling it myself and providing a custom tcp stream to the library) ?

**Comment by Keruspe** [comment]
Hi,

It is possible but not yet documented, I'll try and make an example for that

**Comment by axelfaure** [comment]
That would be great, thank you !

**Comment by Keruspe** [comment]
Actually had to make a few internals public to make it work.

This should do what you want: https://github.com/sozu-proxy/lapin/blob/master/examples/custom_tls_connection.rs

**Comment by Keruspe** [comment]
Note that while this is possible, I definitely agree that it's suboptimal. Will look at what could be done to make things easier, maybe with some queryparams in the querystring to make it automatic

**Comment by axelfaure** [comment]
Thanks, we were able to connect the server using this new version !

On a side note, I doubt providing client certificates through querystring would be a good idea. 
I think you should rather consider adding a different function (or an optional Identity parameter) if you want to handle it natively. However, you may run into additional issues since I think you rely on tcp-stream which does not seem to accept such parameter.
Please note that I am not sure I correctly understood what you were proposing so this comment could very well be irrelevant.

Thank you for the help regarding this issue anyway

**Comment by Keruspe** [comment]
Yeah, not sure about the implementation details yet, but I’ll for sure add a simpler way to do that.
Support in tcp-stream is not a problem if needed, as I’m also the author of that crate :)

**Comment by Keruspe** [comment]
@axelfaure 0.27.0-beta.5 has a new connect_with_identity method

**Comment by axelfaure** [comment]
Exactly what we were looking for, thank you ! (It seems to work by the way ;) )

I guess we could close this issue now

**Comment by Keruspe** [comment]
Thanks for confirming!
