### ISSUE TITLE
Endless busy loop when writing is blocked

### ISSUE THREAD

**Issue by bugaevc** [sozu-proxy/lapin#201]
To reproduce: send messages a lot faster than the MQ server can process them, and as the connection becomes blocked watch the `io_loop` thread use up 100% of a CPU core while doing no useful work. Connect with `strace` and see if perform `epoll`s with zero timeout, endlessly.

I've tried to investigate why this happens; what follows is a short summary.

I don't understand what precisely this block is intended for:

https://github.com/sozu-proxy/lapin/blob/2b2627ce926b18d19b2939000bb252a2a02a5048/src/io_loop.rs#L279-L298

But here's what happens when either the connection is explicitly blocked with `connection.blocked`, or the socket is just full (so `self.can_write` is `false`), and there's no incoming data (so `self.can_read` is `false`):

* `self.wants_to_read()` is `false`, so we get into the outer `if`
* `self.status != Status::Stop`
* `self.has_data` may well be true if there are queued messages

so, `set_readiness` is set to readable; meaning `mio::Poll::poll` returns without waiting and this whole thing repeats over and over in an endless busy loop.

Again, I'm not sure my intuition about what `CONTINUE` is supposed to be is right (some comments would help!), but it looks like is has to do with waking up the loop when there is new data to be sent out. But `poll`-ing should return when `can_read || (has_data && can_write && !blocked)`, not when `can_read || has_data || can_write`.

P.S. Is there any way I/O could be redone on top of Tokio reactor, instead of hand-rolling I/O loop on top of mio?

**Comment by Keruspe** [comment]
Hi,

Indeed, the blocked connection is not correctly handled here.
Fix is being published in 0.26.8

Lapin is designed to run outside of tokio (while being compatible with tokio), that's why it's not built on top of the tokio reactor.
Continue is there to wake up the io loop when there's still stuff that needs processing and we didn't reach WOULDBLOCK yet

**Comment by bugaevc** [comment]
Thanks for responding so quickly!

I'm afraid there is still an issue when sending is blocked not because of explicit `connection.blocked` from the server, but simply because the socket is full.

> Lapin is designed to run outside of tokio (while being compatible with tokio), that's why it's not built on top of the tokio reactor.

Yes, but that doesn't mean it cannot use tokio internally as an implementation detail instead of using mio directly; and then if you do, it would make sense to expose that, i.e. make it not an implementation detail.

> Continue is there to wake up the io loop when there's still stuff that needs processing and we didn't reach WOULDBLOCK yet

Why not just continue the inner loop in that case?

**Comment by Keruspe** [comment]
> Thanks for responding so quickly!
> 
> I'm afraid there is still an issue when sending is blocked not because of explicit `connection.blocked` from the server, but simply because the socket is full.
> 

When the socket is full, can_write is false: https://github.com/sozu-proxy/lapin/blob/master/src/io_loop.rs#L244
Are you sure the connection is blocked and you do not get some channel flow set to false instead? (Which, as mentioned in #202, is probably still a problem)

> 
> Yes, but that doesn't mean it cannot use tokio internally as an implementation detail instead of using mio directly; and then if you do, it would make sense to expose that, i.e. make it not an implementation detail.
>

We used to do that, but it was even worse, we were forced to abuse the task wakers to keep things going on and it resulted on basically doing the same, but with less control and more overhead

> 
> Why not just continue the inner loop in that case?

We use that when either there's nothing left to read or nothing left to write (or when we cannot read or write on the socket), to issue a call to poll to check if this has changed or not.

**Comment by Keruspe** [comment]
(I'm currently checking what needs to be done wrt channel flow, which is a bit trickier as it only matters from some kind of frames and not all of them)

**Comment by bugaevc** [comment]
> When the socket is full, can_write is false

Yes, but (unless I'm missing something) it doesn't prevent any of these `if`s, see my description above.

> We use that when either there's nothing left to read or nothing left to write (or when we cannot read or write on the socket), to issue a call to poll to check if this has changed or not.

TBH I still don't understand why is that correct.

**Comment by Keruspe** [comment]
Oh, I think I know what's going on in your case, actually.
So, the socket is full, can_write is false. Let's say at this point the server isn't writing back either, so can_read is false too.
When we issue a call to poll, here are the things that can make the call to poll return and trigger a new iteration of the event loop:
- the server writes something back, can_read becomes true and we go on with the event loop _ that's not the case here
- the socket is now available for writes, can_write becomes true and we go on with the event loop _ that's not the case here either
- we sent a CONTINUE on last iteration _ that's not the case here either (unless connection is not blocked? I have some work i a local branch which reworks that part a little, have to give it a further look)
- the connection sends us some new data to send (e.g. you're still calling basic_publish or doing other actions)

**Comment by Keruspe** [comment]
0.26.9 has a trivial fix for the third point (which I honestly thought was already like this as of starting to write the previous message).
If you're still seeing a busyloop with 0.26.9, It's because of the last point above.

**Comment by Keruspe** [comment]
> TBH I still don't understand why is that correct.

Let's take a simple scenario:
- there is nothing to read (the server didn't send you anything)
- you publish a lot of messages really fast (faster than your connection can handle)

If we keep looping without going back through poll, we won't know if there is any new incoming message as our state is still can_read = false.

Currently we do it on each iteration if either can_read or can_write is false. There is clearly room for improvement, that's what #202 is about, but something like this is necessary anyways.
I have several possibilities locally inspired by tokio-reactor, async-std and the likes

**Comment by bugaevc** [comment]
> Oh, I think I know what's going on in your case, actually.
So, the socket is full, can_write is false. Let's say at this point the server isn't writing back either, so can_read is false too.
When we issue a call to poll, here are the things that can make the call to poll return and trigger a new iteration of the event loop:
> * the server writes something back, can_read becomes true and we go on with the event loop _ that's not the case here
> * the socket is now available for writes, can_write becomes true and we go on with the event loop _ that's not the case here either
> * we sent a CONTINUE on last iteration _ that's not the case here either (unless connection is not blocked? I have some work i a local branch which reworks that part a little, have to give it a further look)
the connection sends us some new data to send (e.g. you're still calling basic_publish or doing other actions)

I'm not sure that is what I experience in practice, but the third point is what I think is (or would be) happening, yes: the socket is full (unwritable) and unreadable and `has_data` is true, so last iteration sets `CONTINUE` to readable, so we get there again and set do it again and again.

**Comment by Keruspe** [comment]
@bugaevc we now check for can_write (wouldblock) here too in 0.26.9, are you still having troubles with it?

If you do I'd be interrested in seeing trace logs

**Comment by bugaevc** [comment]
> Let's take a simple scenario:
> * there is nothing to read (the server didn't send you anything)
> * you publish a lot of messages really fast (faster than your connection can handle)
> If we keep looping without going back through poll, we won't know if there is any new incoming message as our state is still can_read = false.

In this case of course you need to poll, but you don't need an extra `CONTINUE`, you want to wait for the socket becoming either readable or writable.

I would imagine the loop should work like this (in pseudocode-ish Rust):
```rust
loop {
    poll.poll();
    can_write = ...;
    can_read = ...;
    while can_read {
        if read() == Err(WouldBlock) { can_read = false; }
    }
    while can_write && have_data && !connection_blocked {
        if write() == Err(WouldBlock) { can_write = false; }
    }
    if can_write && !connection_blocked {
        poll.register_interest(NEW_DATA);
    } else {
        poll.deregister_interest(NEW_DATA);
    }
}
```

the existing loop does things differently; it doesn't deregister `CONTINUE` (called `NEW_DATA` above) when it cannot write, so it'll be woken up each time a message is sent even if it's blocked, and it has this clause for setting `CONTINUE` readable from the loop itself; and I don't understand what difference does it make exactly, and why.

> @bugaevc we now check for can_write (wouldblock) here too in 0.26.9, are you still having troubles with it?

I haven't tested that yet, let me see...

**Comment by bugaevc** [comment]
Looks like this doesn't happen anymore :tada:

I still believe what I've sketched above would be better, but it doesn't eat CPU when blocked anymore, so I'll close this. Thanks again!

**Comment by Keruspe** [comment]
Keeping trace of your above comment in #202 for further iteractions.
Thanks for the report and feedback, really appreciated!

**Comment by bugaevc** [comment]
> Is there any way I/O could be redone on top of Tokio reactor, instead of hand-rolling I/O loop on top of mio?

I feel that I should add some context to why I would want something like this. Generally, I don't think it's acceptable for a Rust crate to implicitly spawn an I/O loop thread / reactor. This is an expectation that is set up by Rust "not having a runtime" and being usable in contexts such as a plugin to an existing app or service.

Now, if course lapin needs *some* I/O loop to keep track of the connection, but I would expect the user of the crate to have control over which one is used and how its lifetime is managed (by that I mean when it gets created and destroyed).

Perhaps I want the loop to run in-thread (in the same thread that I process the messages) or indeed as a separate thread, perhaps as a separate thread with a higher or lower priority. If I'm already using a reactor (such as tokio's), I would like lapin to integrate into that reactor instead of spawning its own; the same goes for when I'm only writing a plugin for an existing app that uses e.g. `CFRunLoop` — I would want lapin to use the same platform-provided reactor the host app uses.

One way to make this feasible is to make a trait describing what lapin needs from a reactor and then implement it for various reactor types (including the built-in one). Or does such a trait already exist in the ecosystem?

**Comment by Keruspe** [comment]
Opened #205 for this.

Note that any crate using e.g. async-std and doing I/O will get a new I/O thread no matter if run with another reactor or not, for example, and I'm pretty sure more crates like that are going to be released within next months

**Comment by bugaevc** [comment]
> Opened #205 for this.

👍

> Note that any crate using e.g. async-std and doing I/O will get a new I/O thread no matter if run with another reactor or not, for example, and I'm pretty sure more crates like that are going to be released within next months

Yeah, that I don't like either :D
