### ISSUE TITLE
Error in README example

### ISSUE THREAD

**Issue by gasabr** [sozu-proxy/lapin#214]
Example goes like this
``` rust
  info!("will consume");
  channel_b.clone().basic_consume("hello", "my_consumer", BasicConsumeOptions::default(), FieldTable::default()).wait().expect("basic_consume").set_delegate(Box::new(Subscriber { channel: channel_b }));
```
Although, the[ docs state](https://docs.rs/lapin/0.28.0/lapin/struct.Channel.html#method.basic_consume) that the first parameter should be lapin::Queue

Also, instead of signature in the docs and example 1.39 compiler says `on_new_delivery` should look like this
``` rust 
fn on_new_delivery(&self, result: Result<Option<Delivery>, lapin::Error>)
```

**Comment by gasabr** [comment]
I'll submit PR after fixing the first issue, can not figure out how to initialize Queue at the moment

**Comment by Keruspe** [comment]
You get a queue when using queue_declare.
The example in the README is cupposed to be a copy of another example, it' probably out of sync, will check

**Comment by Keruspe** [comment]
Should be fixed
