### ISSUE TITLE
support async await

### ISSUE THREAD

**Issue by andrewbanchich** [sozu-proxy/lapin#217]
Is there any work being done on upgrading `lapin-futures` to use `std::future`?

**Comment by Keruspe** [comment]
Yep: don't use lapin-futures, it's futures-0.1 only.

Lapin now has a futures feature for futures-0.3 and async await, see https://github.com/sozu-proxy/lapin/blob/master/examples/pubsub_futures.rs

**Comment by andrewbanchich** [comment]
Ah, I see. Awesome, thanks!

**Comment by jerry73204** [comment]
I see it requires `futures` feature. Suppose we can document it in README?

**Comment by Keruspe** [comment]
Sure !

**Comment by Keruspe** [comment]
I'll gladly accept a pull request documenting that :)

**Comment by andrewbanchich** [comment]
@Keruspe Since async await is stable now, any thoughts on setting the `futures` feature on by default?

**Comment by Keruspe** [comment]
Will do in 0.29
