### ISSUE TITLE
Make ::lapin::consumer::ConsumerIterator public

### ISSUE THREAD

**Issue by agodnic** [sozu-proxy/lapin#218]
Hi!

I'm trying to implement a custom iterator that wraps `::lapin::consumer::into_iter()`, but found that `::lapin::consumer::ConsumerIterator` is private (because the module `consumer` is private).

Would it be reasonable to re-export `::lapin::consumer::ConsumerIterator` as `::lapin::ConsumerIterator`?

**Comment by Keruspe** [comment]
Hi,

Sure, can you make a PR on top of the 0.28 branch?

**Comment by agodnic** [comment]
Sure! I'll look into it tonight

**Comment by Keruspe** [comment]
0.28.3 published
