### ISSUE TITLE
Default frame_max is very low

### ISSUE THREAD

**Issue by michaelklishin** [sozu-proxy/lapin#22]
I see that default frame size is set to `8192` while in most clients it is set to `0` which means the server default (`131072`) will be used.

What's the idea behind using such small frames? This value does not control TCP buffer size and therefore you won't reduce [connection memory usage](http://www.rabbitmq.com/networking.html) that way.

**Comment by Geal** [comment]
there's no special idea, I used that as default buffer size in the async library before I moved the buffer management outside of the state machine. What would you recommend, setting 0 as well? Is this a property that people often try to change?
