### ISSUE TITLE
Github build failing

### ISSUE THREAD

**Issue by asevans48** [sozu-proxy/lapin#221]
The library appears to work but I am having trouble convincing myself it is ready for use in a framework when Github lists the build as failing.

Is there a way to resolve this? Do you have a gitter or something more appropriate for this question?

**Comment by Keruspe** [comment]
Hi,

The build on stable and beta succeeds, only the nightly one is failing. I should just mark it as allowing failures. Most of the time it fails because of some timeouts actually installing rust...

**Comment by Keruspe** [comment]
So:

- I disabled everything but nightly when working on async await
- Travis broke their rust nightly
[ ... ]
- Travis changed their default distro on their runners but rabbitmq works out of the box only on the former ones
- I reenabled everything and forced the old distro
- Everything is now green

**Comment by asevans48** [comment]
Thanks. Really like what you are doing :)
