### ISSUE TITLE
Handling of message rejection

### ISSUE THREAD

**Issue by axelfaure** [sozu-proxy/lapin#225]
Hi!

That's more of an open question than an actual issue at that point but I couldn't figure out if/how the return listener mechanism was handled by lapin.

What I am referring to is the handling of message rejection in response to our `basic_publish`. (see pika: [add_on_return_callback](https://pika.readthedocs.io/en/stable/modules/channel.html#pika.channel.Channel.add_on_return_callback))
I guess it is somehow linked to the `on_basic_return_received` function in `channel.rs` but I don't exactly get how it is used.
Is it directly handled through the Confirmation object returned after a `basic_publish` or is there another way to deal with it?

**Comment by Keruspe** [comment]
For now, the way it's implemented in lapin is:

- You enable the mechanism using channel.confirm_select()
- You publish messages
- You call channel.wait_for_confirms() which will wait for all pending confirmations and return the list of rejected messages if any

**Comment by axelfaure** [comment]
Ok, I didn't get the purpose of these methods indeed. 
Thank you!
