### ISSUE TITLE
lack of example for re-development

### ISSUE THREAD

**Issue by yutiansut** [sozu-proxy/lapin#228]
hi, i found out the lapin from the rabbitmq/examples , and in that repo, the lapin's example is too old for current version(^0.28), but using current repo, i just found out something very simple which lack 

- fanout model 
- direct routing
- topic 

and both without something like "queue_bind", "exchange" which can't be ignore 

and in future's example, the code is in "0.27" which not compact with current stage

thanks

**Comment by Keruspe** [comment]
Hi,
More examples would totally be welcome!
I can help if needed

**Comment by Keruspe** [comment]
All examples are using latest version of lapin now
