### ISSUE TITLE
with_kind method

### ISSUE THREAD

**Issue by fecetrulo** [sozu-proxy/lapin#229]
Hi, i got a couple questions.

This method [with_kind](https://docs.rs/lapin/0.28.4/lapin/protocol/basic/struct.AMQPProperties.html#method.with_kind) sets the [type](https://www.rabbitmq.com/releases/rabbitmq-java-client/v3.5.4/rabbitmq-java-client-javadoc-3.5.4/com/rabbitmq/client/AMQP.BasicProperties.Builder.html#type(java.lang.String))`rabbitmq` variable? 
If so, it wouldn't be better to call it `with_type` instead?

**Comment by Keruspe** [comment]
`type` is a reserved keyword in rust. We renamed it to `kind` everywhere (as there are places where we use it without any prefix or suffix) for consistency's sake, but left the original one in the description for protocol documentation purposes.

We would add `with_type` as an alias if you think this would be useful

**Comment by fecetrulo** [comment]
Thanks for the response. I don't think it will be necessary.
