### ISSUE TITLE
redelivered message is missing its "message id" property value

### ISSUE THREAD

**Issue by Dowwie** [sozu-proxy/lapin#232]
A message sent via topic exchange to a queue where durable=true will re-attempt delivery.  I've found that within the properties of the re-attempted delivery there is no message-id when there *was* a message-id in the initial attempt.

**Comment by Keruspe** [comment]
What do you mean by `re-attempted delivery`?
Do you mean the messages returned by `wait_for_confirms`?

**Comment by Dowwie** [comment]
The scenario is as follows:  a topic-exchange consumer gets a message from its queue.  Within the properties of this message is a message-id field with a populated value (defined by the publisher). Something happens that prevents the consumer from sending an ACK (failure, interrupt/shutdown, etc).  Subsequent request for messages from the queue will eventually re-send the message that failed during processing.  This message will not contain the message-id field within its properties anymore.

**Comment by Keruspe** [comment]
Lapin is not in charge of doing that, the AMQP server tracks the received ack and requeues the message itself if needed. I'm not sure what we can do in lapin wrt this? (Or am I missing something there?)

**Comment by Dowwie** [comment]
Thanks for confirming that this is outside the scope of lapin.  I've simply stopped relying on the message_id param and instead include one in the message itself.  Thanks!
