### ISSUE TITLE
An attempt to use a NotConnected socket on Windows

### ISSUE THREAD

**Issue by pdolezal** [sozu-proxy/lapin#236]
I got a weird error when creating a new connection that suggests a possible race condition IMHO. The symptoms that lead to such an opinion are:

- the error occurs on release build only,
- the error does not occur when increasing logging level, which undoubtly has timing impacts.

I was able to extract a minimalistic example that reproduces the error reliably… well on a particular machine at least. A different machine (unfortunately with different specs) works fine. Anyway, perhaps this report helps to discover a well hidden bug.

The machine runs on Windows 7 with *rustc 1.41.1 (f3e1a954d 2020-02-24), stable-x86_64-pc-windows-msvc*.

I used following code:

```rust
use lapin::{Connection, ConnectionProperties};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    env_logger::init();
    let addr = "amqp://localhost:5672/%2f";
    let connection = Connection::connect(&addr, ConnectionProperties::default()).await?;

    tokio::signal::ctrl_c()
        .await
        .expect("failed to install CTRL+C signal handler");

    connection.close(200, "Bye").await?;
    Ok(())
}
```

```toml
[package]
name = "crash"
version = "0.1.0"
authors = ["somebody <somebody@example.org>"]
edition = "2018"

[dependencies]
env_logger = "0.7"
lapin = "0.32"
tokio = { version = "0.2", features = ["full"] }
```

When running the release build with less than `debug` log level, I get:

```
[2020-03-02T18:37:05Z ERROR lapin::io_loop] error reading: IOError(Os { code: 10057, kind: NotConnected, message: "A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied." })
[2020-03-02T18:37:05Z ERROR lapin::connection] Connection error
Error: IOError(Os { code: 10057, kind: NotConnected, message: "A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied." })
```

Is there anything else I could try?

**Comment by Keruspe** [comment]
Hi,

This is a problem specific on windows indeed. The underlying mio TcpStream is considered connected, readable and writable, lets us write to it, but then gives us the info that it's not connected when trying to read from it.

Could you try again with lapin 0.33.0-beta.1? It uses mio 0.7 which has lots of windows fixes (a complete rewrite, actually)

**Comment by pdolezal** [comment]
I could not reproduce the problem with 0.33.0-beta.1 on neither of my Windows machines. Because it seems to be a known problem :wink: I think it might be solved by the `mio` upgrade indeed.

Thanks.

**Comment by Keruspe** [comment]
great thanks for confirming!
