### ISSUE TITLE
Possible bug in `ConfirmationFuture`

### ISSUE THREAD

**Issue by Patryk27** [sozu-proxy/lapin#238]
Hi :-)

I think there's a possible bug in the way `ConfirmationFuture` is currently implemented - right here:
```rust
impl Default for Watcher {
    fn default() -> Self {
        Self(task::current())
    }
}

/* ... */

impl<T: Send + 'static, I: 'static> Future for ConfirmationFuture<T, I> {
    /* ... */

    fn poll(&mut self) -> Poll<Self::Item, Self::Error> {
        if !self.0.has_subscriber() {
            self.0.subscribe(Box::new(Watcher::default()));
        }

        /* ... */
    }
}
```
As far as I understand, `task::current()` _can change_ in-between `poll()`-s (e.g. when executor moves this future onto other thread [^1]) and so the notification can get lost.

I haven't been able to reproduce this, but docs describe it as a likely situation.

[^1] This case seems similar to the one described near `shared_state.waker = Some(cx.waker().clone());` in here: https://rust-lang.github.io/async-book/02_execution/03_wakeups.html#applied-build-a-timer

**Comment by Keruspe** [comment]
When the ConfirmationFuture first gets polled, we register the polling task, and wake it once we're ready. The executor isn't supposed to poll us again until it gets a notification.
Note that what you describe here was a flaw in futures 0.1 design and only affects lapin-futures which is a compatibility layer for futures 0.1 which will officially be deprecated in a couple of days.

**Comment by Patryk27** [comment]
> The executor isn't supposed to poll us again until it gets a notification.

But it can, right?

The fact that executors usually try to minimize the work and avoid repeatedly calling `poll()` is just an implementation detail - technically they are free to do basically `loop { task.poll(); }` until completion.

> _[this case]_ only affects lapin-futures which is a compatibility layer for futures 0.1 which will officially be deprecated in a couple of days

Well, if so, then it may not be worth investigating it further :-)

**Comment by Keruspe** [comment]
After re reading the code and the passage you linked to (very useful, thanks a lot), it seems to be affecting the futures 0.3 integration too

**Comment by Patryk27** [comment]
Since the original issue's been resolved, I'm just gonna go and close this issue - thanks! :-)
