### ISSUE TITLE
Have a way to access individual publisher confirms after basic_publish

### ISSUE THREAD

**Issue by jothan** [sozu-proxy/lapin#243]
I'm doing some latency sensitive work (RELP log forwarding to AMQP) and since the RELP protocol acknowledges messages individually, I can't afford to do Channel::wait_for_confirms once in a while. I also do not want to sacrifice reliability. Our current log adapter in Python with pika can do this in a fully pipelined fashion.

It would be very nice if the return value of basic_publish could be waited on for confirmation (or converted into something that can be waited on).

**Comment by Keruspe** [comment]
Fun fact: it used to be the case, and it was modified because the rabbitmq documentation says it’s a very bad idea to do so, and that the broker isn’t guaranteed to be able to do that and often just batch the notifications.
I’ll see how easy it would be to optionally restore this behaviour

**Comment by jothan** [comment]
In some of our other workflows, we do indeed ack like 5000 messages at a time, but in my use case the upstream protocol expects individual confirmations. This also applies to code that will interface SMTP to AMQP soon.

I agree with the Pivotal folks that it is not a good idea in most cases. I'm a bit of an outlier in than I'm doing reliable/durable messaging that is hitting disk in most of workflows.

**Comment by Keruspe** [comment]
Would you like to get some id from the basic_publish for which you can wait for confirm? (In this case, how would the basic_return be handled?)
Or would you like some kind of « consumer » which receives all the ack/nack/basic_return? (this would be real quick to implement I think)

**Comment by jothan** [comment]
If I had the choice, I would prefer to be able to wait on a single id (the first option you mentionned). At least with RabbitMQ, I think message returns precede the nack, therefore it should be possible to return the message to the matching publish call.

**Comment by jothan** [comment]
https://www.rabbitmq.com/publishers.html I think I found the section you were mentionning here called "Publish-and-Wait". Since messages are published many at a time (while still handling individual ACKs), I do not suffer from a throughput hit. The RabbitMQ docs call my use case "Streaming Confirms".

**Comment by Keruspe** [comment]
Ok, I know how I’m going to implement this

**Comment by Keruspe** [comment]
Just pushed the first step for this.

Now, `basic_publish(...).await?` will give you an `Option<PinkySwear<()>>`, which is Some when publishers_confirm is enabled or None otherwise.
You can then await the given PinkySwear to wait for ack/nack.

Next step is to make it carry whether the message was ack'ed or nack'ed, then the returned message if we can

**Comment by Keruspe** [comment]
Simplified `Option<PinkySwear<()>>` to `PinkySwear<PublisherConfirm>` where `PublisherConfirm` is one of `Ack`, `Nack` or `NotRequested`.

Last question is how we decide if we want to dispatch the returned message in this `PublisherConfirm::Nack` or in the local storage for the next `wait_for_confirms` call.

**Comment by jothan** [comment]
Thanks, I will give this a try this week !

**Comment by Keruspe** [comment]
`Nack` now carries the returned message, but it's also stored for `wait_for_confirms`.

`PinkySwear<Result<PinkySwear<PublisherConfirm>>>` is a bit cumbersome. I'll probably wrap this in a struct with two methods, one returning `PinkySwear<Result<()>>` as before, another returning `PinkySwear<Result<PublisherConfirm>>` (e.g. flattening the two PinkySwears). This will allow chosing whether we want to store the message for `wait_for_confirms` or not

**Comment by Keruspe** [comment]
In the end, basic_publish now returns a `PinkySwear<Result<PublisherConfirm>>`.
`PublisherConfirm` is basically the same as a `PinkySwear<Confirmation>` from a use PoV.
`Confirmation` can be `Ack`, `Nack(BasicReturnMessage)` or `NotRequested`.
If you drop the `PublisherConfirm` without getting the associated `Confirmation`, it will get available in `wait_for_confirm`.

I'll probably do a release tomorrow

**Comment by Keruspe** [comment]
See https://github.com/sozu-proxy/lapin/commit/66b65779ac922b89df89d4681833597b5cd406a5 for an example.

#245 might have delayed this release a little, I still have one other thing I want in it so it might only happen tomorrow

**Comment by Keruspe** [comment]
0.35.0 has been released
