### ISSUE TITLE
Example for `wait_for_confirms`

### ISSUE THREAD

**Issue by pfernie** [sozu-proxy/lapin#244]
Is there a good example of the `wait_for_confirms()` behavior for publisher confirm? I see it referenced in a number of issues that one can essentially `confirm_select()` on the channel and then `wait_for_confirms()`. However, if I take the simple `examples/connections.rs` and [adapt it slightly](https://gist.github.com/pfernie/0f06a44a5f300963829c598af5a9a2af), I essentially see hanging behavior. The `await` on l.59 never resolves. With `trace` enabled, I do see the `io_loop` and such processing messages, including the broker's `Ack` of the published message; it seems the promise return by `wait_for_confirms` is never fulfilled, however.

Interestingly, if, instead of `await`, I explicitly call `.wait()` on the promise, the example successfully completes. So I may simply be trying to `await` in the wrong context here?

**Comment by Keruspe** [comment]
Ok, this is now fixed in pinky-swear 1.3.0 which cargo update should pick up.

Thanks a lot for the report! Feel free to make a pull request to add such an example if you'd like :)

**Comment by Keruspe** [comment]
Fwiw, I just added https://github.com/sozu-proxy/lapin/commit/66b65779ac922b89df89d4681833597b5cd406a5

**Comment by pfernie** [comment]
Thx very much for the fix & new example!
