### ISSUE TITLE
Connection Pool availability

### ISSUE THREAD

**Issue by kumarmo2** [sozu-proxy/lapin#273]
Hi, I am a noob in rust, so this might be a silly question. I wanted to confirm is there any connection pool/channel pool maintained by the library ? 

I have glimpsed through the source code and I couldn't find any. But being a noob in rust, I just wanted to confirm.

**Comment by Keruspe** [comment]
There is no pooling available in the library, you are right. What is your need?

**Comment by kumarmo2** [comment]
My application is going to make quite a few channels/connections. So I was looking to make a pool of channels and connections.

**Comment by Keruspe** [comment]
I fail to see how it fits with the whole AMQP model. I don’t think that’s something we want to do in lapin itself.

**Comment by kumarmo2** [comment]
Yeah. I get that it should not be the responsibility of the lapin. I have implemented the pool using r2d2. But thanks for the reply. I will close the issue now.
