### ISSUE TITLE
Timeout on connection

### ISSUE THREAD

**Issue by Zedjones** [sozu-proxy/lapin#274]
Hello, I tried searching through the connection properties and the docs for a connection timeout but I couldn't find anything. Is there a way to wait a certain amount of time for the server to come online instead of instantly throwing an error? 

Thanks in advance

**Comment by Keruspe** [comment]
I have never seen such a feature in any library, do you know of any doing that?

I think it’s better to do that in your application.

**Comment by Zedjones** [comment]
Yeah, certainly. I think the [Java client](https://www.rabbitmq.com/releases/rabbitmq-java-client/v3.5.6/rabbitmq-java-client-javadoc-3.5.6/com/rabbitmq/client/ConnectionFactory.html#setConnectionTimeout(int)) does so.

**Comment by Zedjones** [comment]
It's also in the [URI spec](https://www.rabbitmq.com/uri-query-parameters.html) for RabbitMQ as well. I tried setting that but it didn't do anything.

**Comment by Keruspe** [comment]
Should be fixed now using the connection_timeout query param in the uri!

**Comment by Zedjones** [comment]
Awesome, thanks so much for fixing it quickly! I noticed that on a recent commit you made Channel !Clone. Is the idiomatic way to get a copy of a channel now to just wrap it in an Arc? Thanks in advance

**Comment by Zedjones** [comment]
Also, as a heads-up, this doesn't seem to work:
```rust
let addr = std::env::var("RABBITMQ_ADDR").unwrap_or("127.0.0.1".to_string());
let uri = format!("amqp://{}:5672?connection_timeout=10000/%2f", addr);
let conn = Connection::connect(&uri, ConnectionProperties::default()).await.unwrap();
```
I get this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Custom { kind: Other, error: "invalid digit found in string" })', src/main.rs:89:16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in Arbiter thread.
```
Am I doing something wrong? Maybe I'm just missing something

**Comment by Keruspe** [comment]
Yeah, Arc is the right way to share a Channel I'd say.

In your example, the timeout is set to "10000/%2f" which is why it fails like this

**Comment by Zedjones** [comment]
Ah, okay, that makes sense. I saw the /%2f in the examples and emulated it, what exactly is that doing? I assume it's a format string for a float, but I don't think it's ever explained. 

Thanks again.

**Comment by Keruspe** [comment]
It’s the « / » vhost, url encoded
