### ISSUE TITLE
Why is Channel no longer Clone?

### ISSUE THREAD

**Issue by jbg** [sozu-proxy/lapin#276]
We have a fairly common pattern in our code that looks like this:

```
let consume_channel = connection.create_channel().await?;
let publish_channel = connection.create_channel().await?;
let stream = consume_channel.basic_consume(...).await?;
let stream_processor = stream.try_for_each(|delivery| {
  let consume_channel = consume_channel.clone();
  let publish_channel = publish_channel.clone();
  async move {
    // do some stuff with the delivery
    // maybe use publish_channel to publish a message
    if it_worked {
      consume_channel.basic_ack(delivery.delivery_tag, Default::default()).await?;
    }
  }
});
tokio::spawn(stream_processor); // or in some cases we select or join with other futures
```

We need to clone() and then move the channel clones into the async block to resolve lifetime issues.

`Clone` was recently removed from `Channel` so we now have to manually wrap the channels in `Arc` to be able to use the same pattern. Should we be achieving this some other way? Was `Clone` removed for a reason?

**Comment by Keruspe** [comment]
Close was there because of some internal needs in lapin and never should have been there i the first place. "forcing" the end user to explicitely wrap it in an Arc makes things more explicit, and was the last necessary step required if we ever want to drop CloseOnDrop at some point.

**Comment by Keruspe** [comment]
Actually, Channel (and Connection) being Clonable was one of the main reasons for the introduction of CloseOnDrop

**Comment by Keruspe** [comment]
Using the same pattern as the one for closing the conection, I just redtored channel deriving Clone.
Will issue an rc2 soon
