### ISSUE TITLE
ConnectionProperties with_tokio() not found

### ISSUE THREAD

**Issue by AdaShoelace** [sozu-proxy/lapin#279]
Even though importing both `use tokio_amqp::*;` and `use lapin::{Connection, ConnectionProperties, Result};` and then running:  
```
let addr = std::env::var("AMQP_ADDR").unwrap_or_else(|_| "amqp://127.0.0.1:5672/%2f".into());
let conn = Connection::connect(&addr, ConnectionProperties::default().with_tokio()).await?;
```  
the compiler says `with_tokio()` can't be found for `ConnectionProperties`.
Am I missing a feature toggle in Cargo.toml or something?

**Comment by Keruspe** [comment]
Which version of lapin and tokio-amqp are you using?

**Comment by AdaShoelace** [comment]
I managed to figure it out and switched `lapin` and `tokio_amqp` to version 1.0.0-rc3 and 0.1.0-rc3 respectively. So this issue can be closed.
