### ISSUE TITLE
Consumer message size limit?

### ISSUE THREAD

**Issue by 6xzo** [sozu-proxy/lapin#280]
I am using 1.0.0-rc3 with async-amqp and no TLS.

If messages are larger than 0.5MB (524,288B), the consumer stream or delegate does not yield them. The same code does properly receive deliveries that are 524,288B or smaller. For the larger messages, I do see in the management GUI that the messages have been transmitted to the client, but that they are not acked. The client just seems to hang.

**Comment by Keruspe** [comment]
Could you provide a reproducer?
Which operating system are you on?

**Comment by 6xzo** [comment]
I am using Ubuntu 18. I'll make a minimal test case.

**Comment by Keruspe** [comment]
Output with RUST_LOG=trace could help too

**Comment by 6xzo** [comment]
Well, in preparing a minimal test case, I've found that I wasn't correct that the boundary between working or not is 0.5MB exactly... With the minimal test case, it almost always works correctly with that message size. At 1MB, it still usually works, but not always; in the most recent run, it received one message and then got stuck. At larger message sizes (4MB) it gets stuck more often, perhaps always.

In addition to a minimal receiver, I'm including a minimal sender I used to test the minimal receiver.

In the attached trace log output, I deleted a lot of repeated text, and indicated where I did so. This trace is for the case where it received one message and then got stuck.

[deps.txt](https://github.com/sozu-proxy/lapin/files/4663688/deps.txt)
[trace2.txt](https://github.com/sozu-proxy/lapin/files/4663677/trace2.txt)
[receiver.rs.txt](https://github.com/sozu-proxy/lapin/files/4663638/receiver.rs.txt)
[sender.rs.txt](https://github.com/sozu-proxy/lapin/files/4663639/sender.rs.txt)

**Comment by Keruspe** [comment]
I assume you use `with_async_std()`?
Can you reproduce if you replace this wit just `with_async_std_executor()` which will use async-std's executor but lapin's reactor?
Can you reproduce with rc4?

**Comment by 6xzo** [comment]
Yes, I have been using `with_async_std()`. I replaced with `with_async_std_executor()` and the behavior is the same.

I tried `"=0.1.0-rc4"` at both lapin and async-amqp, but I get a compilation error in `tcp-stream`:

```
   Compiling tcp-stream v0.19.0
error[E0596]: cannot borrow `config.cert_chain` as mutable, as `config` is not declared as mutable
   --> /home/jking/.cargo/registry/src/github.com-1ecc6299db9ec823/tcp-stream-0.19.0/src/lib.rs:274:31
    |
246 |     config: TLSConfig<'_, '_, '_>,
    |     ------ help: consider changing this to be mutable: `mut config`
...
274 |     if let Some(cert_chain) = config.cert_chain.as_mut() {
    |                               ^^^^^^^^^^^^^^^^^ cannot borrow as mutable
```

**Comment by Keruspe** [comment]
Heh, sorry about that, should be fixed in tcp-stream 0.19.1

**Comment by Keruspe** [comment]
Ok I actually can reproduce.
For some reason the socket is readable but we read 0 and get readable events continuously which triggers a busy loop

**Comment by Keruspe** [comment]
This is now fixed in master.

I also found another issue, once this one is fixed, I'll make a new rc (hopefully the last)

**Comment by 6xzo** [comment]
I pointed at master for `lapin` and `async-amqp`, but I run into an error with that same minimal receiver test case now:

```
[2020-05-21T21:12:46Z DEBUG lapin::channels] create channel with id 0
[2020-05-21T21:12:46Z DEBUG lapin::io_loop] Connecting to 127.0.0.1:5672
[2020-05-21T21:12:46Z DEBUG lapin::channel] Server sent Connection::Tune: Tune { channel_max: 0, frame_max: 131072, heartbeat: 60 }
[2020-05-21T21:12:46Z DEBUG lapin::channels] create channel
[2020-05-21T21:12:46Z DEBUG lapin::channels] create channel with id 1
[2020-05-21T21:12:47Z INFO  receiver] will consume
[2020-05-21T21:12:47Z ERROR lapin::io_loop] Socket was readable but we read 0, marking as wouldblock
[2020-05-21T21:12:47Z ERROR lapin::io_loop] parse error: Error(ParserErrors { error: Nom(Tag), errors: None })
[2020-05-21T21:12:47Z ERROR lapin::channels] Connection error
[2020-05-21T21:12:47Z INFO  receiver] received message
[2020-05-21T21:12:47Z DEBUG receiver] Err(ParsingError(Error(ParserErrors { error: Nom(Tag), errors: None })))
[2020-05-21T21:12:47Z INFO  receiver] done consume
```

Is there any other dependency that I need to change?

**Comment by Keruspe** [comment]
Yes, that’s the issue I mentioned above

**Comment by 6xzo** [comment]
I misunderstood, and apologize. Thank you.

**Comment by Keruspe** [comment]
This is now fixed in rc5.

Thanks a lot for the report!

**Comment by 6xzo** [comment]
It's all working well for me now. Thank you very much.
