### ISSUE TITLE
Force people to declare queues before using them

### ISSUE THREAD

**Issue by Keruspe** [sozu-proxy/lapin#32]
You can't use a queue in a channel that didn't declare it. We should ensure the queue has been declared in the channel somehow, maybe abstracting the queue name in a struct?

**Comment by jeffparsons** [comment]
> You can't use a queue in a channel that didn't declare it

Do you have a link to the part of the spec that describes this? I just went looking for it and couldn't find it!

**Comment by Keruspe** [comment]
"Fixed" by 9df45c7b406faf250b69b8124f0df251db337f6d
