### ISSUE TITLE
Support doing basic_publish directly to exchange

### ISSUE THREAD

**Issue by steve-chavez** [sozu-proxy/lapin#49]
Most amqp libs in different langs and also rust-amqp have this interface for publish: 

```python
channel.basic_publish(exchange='', routing_key='task_queue')
```
Right now lapin specifies a queue as the first argument for basic_publish, declaring the queue upfront is not useful for more complex topologies like when doing exchange to exchange routing.

**Comment by michaelklishin** [comment]
Not allowing publishing to exchanges (that is, forcing the default exchange) in a client means [RabbitMQ tutorials](http://www.rabbitmq.com/getstarted.html) cannot be ported for it.

Convenience functions for "publishing to a queue" are not uncommon but typically use a different name, e.g. `sendToQueue` in Node's amqplib.
