### ISSUE TITLE
Add support for amqp(s):// URIs

### ISSUE THREAD

**Issue by blanham** [sozu-proxy/lapin#51]
I'm using Lapin on Heroku and had to bodge together some boilerplate for translating the amqp://* URIs that are passed in through env vars. There is an official-ish specification (https://www.rabbitmq.com/uri-spec.html) and other libraries like bunny for Ruby have built-in support. (Though there's mention [here](http://rubybunny.info/articles/connecting.html#using_connection_strings) that there are some implementation differences, but I can't imagine they wouldn't be that hard to paper over). I'd be willing to take this on, but I wanted to raise the issue first and see if anyone had any comments. I could envision this either being a method on ConnectionOptions, or even a separate helper function that returns ConnectionOptions and SockAddr together.

**Comment by michaelklishin** [comment]
A separate function makes more sense to me.

I can think of 5 client libraries, including Bunny, that follow the spec document above. Java, .NET client and Bunny (well, amq-protocol) have a decent number of test cases, e.g. https://github.com/rabbitmq/rabbitmq-java-client/blob/65367b50849e6716b0368345faffbf82edfba902/src/test/java/com/rabbitmq/client/test/AmqpUriTest.java and https://github.com/ruby-amqp/amq-protocol/blob/master/spec/amq/uri_parsing_spec.rb.

One part that can still vary is IPv6 address support but PaaS environments such as Heroku usually use domain names anyway.

**Comment by Keruspe** [comment]
I think that should be done in another crate.

we do not want to depend on a specific ssl implementation on lapin. The
boilerplate is not that long (see examples/tls.rs)

**Comment by blanham** [comment]
@Keruspe I'm not sure I follow, there's nothing involving SSL other than perhaps the need for a boolean or enum to indicate the URL is amqps:// vs amqp://

@michaelklishin Hmm, that might be an argument for adding it to https://github.com/sozu-proxy/amq-protocol instead

The no-async amqp crate has a convenience method that does what I propose: https://github.com/Antti/rust-amqp/blob/master/src/session.rs#L300

**Comment by Keruspe** [comment]
Oh, I see, you only want the parsing, not the actual connection.
I'll give it a look.

**Comment by blanham** [comment]
@Keruspe Awesome! I'm totally willing to do the actual implementation.

**Comment by michaelklishin** [comment]
@blanham not necessarily, in Ruby there are multiple clients that would otherwise reinvent the parser. It can go into amq-protocol in Rust or this library.

**Comment by michaelklishin** [comment]
@blanham I'm not a maintainer of this library but since the problem is fairly well defined and there are existing examples to follow, I'd suggest submitting a PR that roughly demonstrates what you have in mind. It's a lot easier to consider a change that's already done ;)

**Comment by Keruspe** [comment]
@blanham Does this look like what you were expecting? https://github.com/sozu-proxy/amq-protocol/commit/a60ce9b4d601c9fa9307ba4c8d3b5591f31fd712
If so I'll shortly make a release with that in

**Comment by michaelklishin** [comment]
@Keruspe please don't. Your test cases do not match the examples on https://www.rabbitmq.com/uri-spec.html, which means this client will parse URis differently from Java, .NET, Ruby and Erlang clients.

**Comment by Keruspe** [comment]
@michaelklishin Should be better now

**Comment by Keruspe** [comment]
I made a small crate around that fwiw, I'll publish it soon.
It will look like this: https://github.com/sozu-proxy/lapin-futures-rustls/blob/master/examples/client.rs
