### ISSUE TITLE
Is connection recovery planned?

### ISSUE THREAD

**Issue by hammett** [sozu-proxy/lapin#70]
Looking at the current design, seems a bit challenging to implement it.

**Comment by michaelklishin** [comment]
It would be great, provided that recovery strategy has been battle tested in at least 6 clients in 4 different programming languages over the course of 3-6 years (depending on the client) ;)

**Comment by Keruspe** [comment]
"battle tested" seems to depend on the context and usage of the clients, we had lots of issues with automatic reconnection with other clients.

We usually either make the program crash and be restarted automatically to get in a clean state, or use tokio-retry around the rabbit future

**Comment by hammett** [comment]
tokio-retry should be enough for our scenarios. thanks

**Comment by Geal** [comment]
@michaelklishin I'd be interested in how connection recovery has been implemented in other clients. Which part of the state do they carry over to the new connections?

**Comment by michaelklishin** [comment]
@Geal take a look at http://www.rabbitmq.com/api-guide.html and http://rubybunny.info/articles/guides.html plus `AutorecoveringConnection`/`AutorecoveringChannel` in the Java client. In Bunny that logic is right in `Bunny::Session`.

There is a bit of difference between those two because their APIs are but those two are fairly representative. All Ruby clients copy Bunny, .NET client and Langohr copy Java client, and so on.

**Comment by hammett** [comment]
The essence is that it needs to restore the state, queues and bindings, and consumers. It also needs to offset the deliverytag used for ack/nack. 
For your client, it would also mean taking ownership of the tcpstream, restoring/replacing it during recovery, while keeping channels/connections objects handed to the user code "valid"

https://github.com/d-collab/RabbitMqNext/blob/master/src/RabbitMqNext/Recovery/RecoveryEnabledChannel.cs#L345

**Comment by michaelklishin** [comment]
Versioned delivery tags (in Bunny parlance) is a nice-to-have, not essential.

I agree that this is a feature that may require a non-trivial amount of refactoring and in languages such as Rust, even API changes.

**Comment by hammett** [comment]
I dont see how the offset of delivery tags is a nice-to-have. If you send a delivery tag without the offset (post recovery) it's an error and the channel is terminated.
