### ISSUE TITLE
multi body frame support

### ISSUE THREAD

**Issue by hammett** [sozu-proxy/lapin#71]
Digging more into the code, I'm not sure the this situation is being handled. Publishing a big message (one which the payload's length - or actually the body frame - is higher than the max frame size) requires splitting. Same thing for message delivery / consuming. 

Is this supported?

Thanks

**Comment by Keruspe** [comment]
Hi,

For basic_get and basic_consume I'm sure it's supported, the state-machine in lapin-async aggregates the frames until the whole message is received before "forwarding" it to lapin-futures.
For basic_publish, I think it's properly handled, I'll double check that.

Fixing the issue title as it seems backwards (but correct me if I'm wrong !)

**Comment by Keruspe** [comment]
I confirm that we correctly split the body into separate frames if it's above frame_max too.

Did you hit any issue wrt that or were you just wondering?

**Comment by hammett** [comment]
I was just wondering after browsing the code. Could you point me to where the payload is split into multiple body messages?

**Comment by Keruspe** [comment]
https://github.com/sozu-proxy/lapin/blob/master/async/src/connection.rs#L613

**Comment by hammett** [comment]
Parfait. Merci!
