### ISSUE TITLE
How to block on waiting for messages

### ISSUE THREAD

**Issue by ihrwein** [sozu-proxy/lapin#79]
Do you know how to use basic_get in a blocking way? If the queue is empty and I call basic_get it returns  "basic get returned empty" error. I'd like to block the calling thread in this case.

According to Keruspe in #73:

> Hi,
>
> for the basic_get stuff, please open a separate issue.
Blocking is not a viable option in a futures-based environment though, I think the right thing to do is rather to wrap the value in an Option or such as basic_get is expected to optionally return something

I don't necessarily need `basic_get` if I can work it around with something else.

I can imagine something like the following code, but it doesn't seem to be the optimal solution:

```
loop {
  msg = basic_get()
  if msg != "empty error" {
    break
  }
  sleep()
} 
```
Do you have any better idea? Thanks!

**Comment by Keruspe** [comment]
Is there any specific reason why you don't use basic_consume?

**Comment by ihrwein** [comment]
Nothing, I just didn't see it in the first place. Let my rewrite my code to see how it works. Thanks!

**Comment by ihrwein** [comment]
Well, it works perfectly. Thanks again!
