### ISSUE TITLE
[FUTURES] no messages on consume queue

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [sozu-proxy/lapin#82]
Hello,

I have an issue with message consuming.
I send messages on queue using rabbitmq, and sometime, I need to restart my rust instance because it don't catch any messages on the queue.
I have a simple configuration (local RabbitMQ, using exchange). regarding RabbitMQ logs the worker looks connected and registered as a consumer on the queue.

Do you have any ideas ? Already seen that ?

Marc-Antoine

**Comment by Keruspe** [comment]
Hi,

Could you paste your code, or a "minimal" reproducer?

**Comment by MarcAntoine-Arnaud** [comment]
Hi,

I used the example provided (I use the 0.8.2 version)

```rust
      channel.queue_declare("mxf_analyser", &QueueDeclareOptions::default(), FieldTable::new()).and_then(move |_| {
        println!("channel {} declared queue {}", id, "mxf_analyser");
        channel.basic_consume("mxf_analyser", "my_consumer", &BasicConsumeOptions::default())
      }).and_then(|stream| {
        println!("got consumer stream");

        stream.for_each(move |message| {
          println!("got message: {:?}", message);
          ...
```

And a the start with `cargo run` sometome I have no `message`. It seams the for_each don't call the event.
On RabbitMQ messages are in unacknowledged state:
`rabbitmqctl list_queues name messages messages_ready messages_unacknowledged` gives:
`mxf_analyser	1	0	1`

which seams Lapin got the message, but don't sent on the for_each.
Marc-Antoine

**Comment by MarcAntoine-Arnaud** [comment]
I just updated and changed the API...
I got the same, when I start, messages pass from the `messages_ready` to `messages_unacknowledged` on RabbitMQ.

**Comment by Keruspe** [comment]
Can you paste your whole source file or push your project somewhere?

**Comment by MarcAntoine-Arnaud** [comment]
I paste here: https://pastebin.com/B72wQwtz
Do you think it can be linked to channel.clone() to publish on it after ?

**Comment by Keruspe** [comment]
Stripping it down to https://gist.github.com/raw/5ad78753b03692094508d01df737407a makes it work, so the issue is after logging the message reception and before doing the ack, not in any lapin code, it seems.

**Comment by MarcAntoine-Arnaud** [comment]
Thanks for the very quick investigation !
Looks okay, but in this case how to publish a message (on an other queue) before sending the ack ?
Because if it's fails, I will be happy to be able to send a nack ...

**Comment by MarcAntoine-Arnaud** [comment]
I try to investigate the way to create a new Core, Channel and Publish message.
It looks better, but I have no message published yet (even if everything seams correct).

**Comment by Keruspe** [comment]
If you use another reactor you'll need to establish a new connection I guess.

I think you can just do something like replacing the ch.ack with some ch.basic_publish.and_then(ch.ack) or something like that

**Comment by MarcAntoine-Arnaud** [comment]
Thanks I created a new reactor and it works fine now.
Good to know !
