### ISSUE TITLE
async:when payload.len() > send_buffer.capacity() : send buffer too small?

### ISSUE THREAD

**Issue by suyanlong** [sozu-proxy/lapin#83]
paste code:

`rust`
extern crate lapin_async as lapin;

use lapin::buffer::Buffer;
use lapin::connection::*;
use lapin::generated::basic;

use lapin::types::*;
use std::{thread, time};
use std::io::Read;
use std::net::TcpStream;
#[test]
fn connection() {
	let mut stream = TcpStream::connect("127.0.0.1:5672").unwrap();
	stream.set_nonblocking(true).unwrap();

	let capacity = 8192;
	let mut send_buffer = Buffer::with_capacity(capacity as usize);
	let mut receive_buffer = Buffer::with_capacity(capacity as usize);
    
	let mut conn: Connection = Connection::new();
	conn.set_frame_max(capacity);
	assert_eq!(conn.connect().unwrap(), ConnectionState::Connecting(ConnectingState::SentProtocolHeader));
	loop {
		match conn.run(&mut stream, &mut send_buffer, &mut receive_buffer) {
			Err(e) => panic!("could not connect: {:?}", e),
			Ok(ConnectionState::Connected) => break,
			Ok(state) => println!("now at state {:?}, continue", state),
		}

		thread::sleep(time::Duration::from_millis(100));
	}
	println!("CONNECTED");
	println!("conn.configuration.frame_max = {}", conn.configuration.frame_max);

	//now connected
	let frame_max = conn.configuration.frame_max;
	if frame_max > capacity {
		send_buffer.grow(frame_max as usize);
		receive_buffer.grow(frame_max as usize);
	}

	let channel_a: u16 = conn.create_channel();
	let channel_b: u16 = conn.create_channel();

	//send channel
	conn.channel_open(channel_a, "".to_string()).expect("channel_open");
	println!("channel [{}] state: {:?}", line!(), conn.run(&mut stream, &mut send_buffer, &mut receive_buffer).unwrap());

	thread::sleep(time::Duration::from_millis(100));
	println!("channel [{}] state: {:?}", line!(), conn.run(&mut stream, &mut send_buffer, &mut receive_buffer).unwrap());

	//receive channel
	conn.channel_open(channel_b, "".to_string()).expect("channel_open");
	println!("[{}] state: {:?}", line!(), conn.run(&mut stream, &mut send_buffer, &mut receive_buffer).unwrap());
	thread::sleep(time::Duration::from_millis(100));
	println!("[{}] state: {:?}", line!(), conn.run(&mut stream, &mut send_buffer, &mut receive_buffer).unwrap());

	//create the hello queue
	conn.queue_declare(channel_a, 0, "hello-async".to_string(), false, false, false, false, false, FieldTable::new())
	    .expect("queue_declare");
	println!("[{}] state: {:?}", line!(), conn.run(&mut stream, &mut send_buffer, &mut receive_buffer).unwrap());
	thread::sleep(time::Duration::from_millis(100));
	println!("[{}] state: {:?}", line!(), conn.run(&mut stream, &mut send_buffer, &mut receive_buffer).unwrap());

	//purge the hello queue in case it already exists with contents in it
	conn.queue_purge(channel_a, 0, "hello-async".to_string(), false).expect("queue_purge");
	println!("[{}] state: {:?}", line!(), conn.run(&mut stream, &mut send_buffer, &mut receive_buffer).unwrap());
	thread::sleep(time::Duration::from_millis(100));

	println!("[{}] state: {:?}", line!(), conn.run(&mut stream, &mut send_buffer, &mut receive_buffer).unwrap());
	conn.queue_declare(channel_b, 0, "hello-async".to_string(), false, false, false, false, false, FieldTable::new())
	    .expect("queue_declare");

	println!("[{}] state: {:?}", line!(), conn.run(&mut stream, &mut send_buffer, &mut receive_buffer).unwrap());
	thread::sleep(time::Duration::from_millis(100));
	println!("[{}] state: {:?}", line!(), conn.run(&mut stream, &mut send_buffer, &mut receive_buffer).unwrap());

	println!("will consume");
	conn.basic_consume(channel_b, 0, "hello-async".to_string(), "my_consumer".to_string(), false, true, false, false, FieldTable::new())
	    .expect("basic_consume");

	println!("[{}] state: {:?}", line!(), conn.run(&mut stream, &mut send_buffer, &mut receive_buffer).unwrap());
	thread::sleep(time::Duration::from_millis(100));

	//println!("[{}] state: {:?}", line!(), conn.run(&mut stream, &mut send_buffer, &mut receive_buffer).unwrap());

	println!("will publish");
	conn.basic_publish(channel_a, 0, "".to_string(), "hello-async".to_string(), false, false)
	    .expect("basic_publish");
	let mut data = b"Hello world!";
	let mut payload: Vec<u8> = vec![];
	payload.resize(8888, 65);
	payload.push(12);
	payload.append(&mut data.to_vec());
	send_buffer.grow(payload.len());
	conn.send_content_frames(channel_a, 60, &payload, basic::Properties::default());
	println!("[{}] state: {:?}", line!(), conn.run(&mut stream, &mut send_buffer, &mut receive_buffer).unwrap());

	thread::sleep(time::Duration::from_millis(100));
	println!("[{}] state: {:?}", line!(), conn.run(&mut stream, &mut send_buffer, &mut receive_buffer).unwrap());
	let msg = conn.next_message(channel_b, "hello-async", "my_consumer").unwrap();

	println!("received message: {:?}", msg);
	println!("data: {}", std::str::from_utf8(&msg.data).unwrap());

}

my code:
`rust`
let mut data = b"Hello world!";
let mut payload: Vec<u8> = vec![];
payload.resize(8888, 65);
payload.push(12);
payload.append(&mut data.to_vec());
send_buffer.grow(payload.len());
conn.send_content_frames(channel_a, 60, &payload, basic::Properties::default());

**Comment by suyanlong** [comment]
my code:
`rust`
let mut data = b"Hello world!";
let mut payload: Vec<u8> = vec![];
payload.resize(8888, 65);
payload.push(12);
payload.append(&mut data.to_vec());
send_buffer.grow(payload.len());
conn.send_content_frames(channel_a, 60, &payload, basic::Properties::default());

**Comment by suyanlong** [comment]
Please help me review it

**Comment by suyanlong** [comment]
when publish,if i set send_buffer.with_capacity(payload.len()), 
on the consumer, how many set receive_buffer.capacity() ???

**Comment by Keruspe** [comment]
Sorry for letting rot so long. Is there still a problem with latests versions?
