### ISSUE TITLE
Add Deserialize and Serialize derive on internal structures

### ISSUE THREAD

**Issue by whitfin** [sozu-proxy/lapin#84]
I'm not sure if this would work or not, but I'm working on a project where I want to load my configuration from a config file. It would be nice if things like `ConnectionOptions` had `#[derive(Deserialize)]` from `serde` to allow reading the configuration through directly. 

Do you think this can/should be added?

**Comment by Keruspe** [comment]
Why don't you deserialize your own struct and then add methods to construct ConnectionOptions and such?

**Comment by whitfin** [comment]
@Keruspe fair enough, that's what I did; makes sense considering you don't have a `serde` dependency. Somehow I thought I saw Serde in this crate before so figured it would've been simple enough :p
