### ISSUE TITLE
Error messages are not bubbling up correctly 

### ISSUE THREAD

**Issue by whitfin** [sozu-proxy/lapin#85]
```
Error { repr: Custom(Custom { kind: Other, error: StringError("failed to handle frame: NotConnected") }) }
```

^ this is the error I see when I bind to a queue which does not exist. I see that there are error messages inside the library that would provide more information which don't seem to come back, such as [here](https://github.com/sozu-proxy/lapin/blob/master/futures/src/channel.rs#L228). This seems like a bug?

**Comment by steve-chavez** [comment]
Seeing the same error message on `lapin-futures=v0.10.0` when running the example in https://github.com/sozu-proxy/lapin/blob/master/futures/examples/client.rs. Solved the error by renaming the `hello` queue in the example.

**Comment by Keruspe** [comment]
Is this problem still here which latests versions? Do you have a minimal reproducer with expected and actual results?

**Comment by Keruspe** [comment]
Should be better in latest versions, closing.
Feel free to open a new issue with a reproducer if needed
