### ISSUE TITLE
A couple of questions about using Lapin crate with external code 

### ISSUE THREAD

**Issue by Relrin** [sozu-proxy/lapin#86]
Hello!

I'm curious about using the Lapin client for a communication with RabbitMQ and have a couple of questions around this library: 
1) Does it possible to make chained and flatten calls for futures from this library?

For example, when we have the following code:
```rust
use lapin_futures_rustls::lapin;
use futures::future::Future;
use lapin::types::FieldTable;
use lapin::channel::{ConfirmSelectOptions, QueueDeclareOptions, QueueDeleteOptions};
use tokio_core::reactor::Core;
use engine::rabbitmq::client::{RabbitMQClient};
use uuid::{Uuid};

fn main() {
    let cli = CliOptions::from_args();
    let mut core = Core::new().unwrap();
    let handle   = core.handle();

    let client = RabbitMQClient::new(&cli);
    let new_future = client.get_future(&handle);  // Returns a connection here 
    let queue_name = format!("{}", Uuid::new_v4());

    core.run(
        new_future
            .and_then(|client| {
                client.create_confirm_channel(ConfirmSelectOptions::default())
            })
            .map_err(|err| {
                let message = format!("Error during creating a channel: {}", err);
                error!("{}", message);
                err
            })

            .map(|channel| {
                let queue_declare_options = QueueDeclareOptions {
                    passive: true,
                    durable: true,
                    exclusive: true,
                    auto_delete: false,
                    ..Default::default()
                };

                channel.queue_declare(&queue_name, &QueueDeclareOptions::default(), &FieldTable::new())
                    .map(|_| channel) // <--- I'd like to return here a channel for using further
            })
            .map_err(|err| {
                let message = format!("Error during declaring the queue: {}", err);
                error!("{}", message);
                err
            })

            .map(|channel| {
                let queue_delete_options = QueueDeleteOptions {
                    if_unused: false,
                    if_empty: false,
                    ..Default::default()
                };

                channel.queue_delete(&queue_name, &QueueDeleteOptions::default())
                    .map(|_| channel)  // <--- and here too
            })
            .map_err(|err| {
                let message = format!("Error during deleting the queue: {}", err);
                error!("{}", message);
                err
            })

            .map(|channel| {
                println!("Channel is closed.");
                channel.close(200, "Close the channel.")
            })

    ).unwrap();
}
```
And trying to compile it, we're getting here the following error of compilation:
```
error[E0599]: no method named `queue_delete` found for type `futures::Map<std::boxed::Box<futures::Future<Item=(), Error=std::io::Error>>, [closure@src/main.rs:112:26: 112:47 channel:_]>` in the current scope
   --> src/main.rs:128:25
    |
128 |                 channel.queue_delete(&queue_name, &QueueDeleteOptions::default())
    |                         ^^^^^^^^^^^^

error: aborting due to previous error
```

2. Can I somehow receive a unique name of a queue, that was generated by RabbitMQ automatically, when the `queue_name` parameter was specified as an empty string, instead of generating a UUID4?

**Comment by Geal** [comment]
Hello,

this error happens because you use `map()` everywhere instead of `and_then`. When you look at examples like this one: https://github.com/sozu-proxy/lapin/blob/master/futures/examples/client.rs#L32-L36

The methods on Channel return futures, so when you do:

```rust
.map(|channel| {
                let queue_declare_options = QueueDeclareOptions {
                    passive: true,
                    durable: true,
                    exclusive: true,
                    auto_delete: false,
                    ..Default::default()
                };

                channel.queue_declare(&queue_name, &QueueDeclareOptions::default(), &FieldTable::new())
                    .map(|_| channel) // <--- I'd like to return here a channel for using further
})
```
the wrapping `map()` call returns a `Map<std::boxed::Box<futures::Future<Item=(), Error=std::io::Error>>`.
So that wrapping `map()` should be a `and_then()`, like this:

```rust
.and_then(|channel| {
                let queue_declare_options = QueueDeclareOptions {
                    passive: true,
                    durable: true,
                    exclusive: true,
                    auto_delete: false,
                    ..Default::default()
                };

                channel.queue_declare(&queue_name, &QueueDeclareOptions::default(), &FieldTable::new())
                    .map(|_| channel) // <--- I'd like to return here a channel for using further
})
```
If you want to reuse the channel afterwards, you can do it like this: https://github.com/sozu-proxy/lapin/blob/master/futures/examples/client.rs#L36-L39

Or something like that might work (I have not tested it):

```rust
channel.queue_declare(&queue_name, &QueueDeclareOptions::default(), &FieldTable::new())
                    .map(move |_| channel)
```

**Comment by Relrin** [comment]
> this error happens because you use map() everywhere instead of and_then. When you look at examples like this one: https://github.com/sozu-proxy/lapin/blob/master/futures/examples/client.rs#L32-L36

Yes, I saw the examples in this crate. In general I'd like to avoid using a nested futures as much as possible because it is harder to read, debug and maintain them further then a simple and flatten futures like in my case here.

I've tried to change the code via `.map(move |_| channel)` in certain places but it also leads the same that were mentioned in the first message.
> Or something like that might work (I have not tested it):
> ```
> channel.queue_declare(&queue_name, &QueueDeclareOptions::default(), &FieldTable::new())
>                     .map(move |_| channel)
> ```

However, replacing the flatten futures `map(...)` calls onto `and_then(...)` solves the issue. That's what I'm looking for. Thank you so much!

**Comment by Relrin** [comment]
But the second question is still interesting for me:
> Can I somehow receive a unique name of a queue, that was generated by RabbitMQ automatically, when the queue_name parameter was specified as an empty string, instead of generating a UUID4?

Also I've mentioned that the created channel doesn't have a `queue_unbind` method, which is leads to errors on compiling stage:
```rust
error[E0599]: no method named `queue_unbind` found for type `lapin_futures_rustls::lapin::channel::Channel<lapin_futures_tls_api::AMQPStream>` in the current scope
   --> src/main.rs:143:25
    |
143 |                 channel.queue_unbind(
    |                         ^^^^^^^^^^^^
    |
    = help: did you mean `queue_bind`?
```
Though I found this method in `lapin-async` crate, the `lapin-futures` doesn't have an implementation for it. So, could you help me with it? Should I go in another way in using it or `lapin-futures` will unbind the the queue from the exchange automatically after using?
