### ISSUE TITLE
Channel.basic_publish should have its `queue` param accurately renamed.

### ISSUE THREAD

**Issue by thedodd** [sozu-proxy/lapin#90]
The futures `Channel.basic_publish` method has a parameter called `queue`, which, when passed down to the underlying async connection, is used as the `routing_key` parameter. I don't know why there is a difference in nomenclature, but calling it `queue` is definitely quite deceptive.

According to the [AMQP 0.9.1 reference](https://www.rabbitmq.com/amqp-0-9-1-reference.html#class.basic), `routing_key` is definitely the correct nomenclature for the `basic publish` argument.

Excellent work on these libraries so far!

**Comment by michaelklishin** [comment]
This client has its fair share of opinionated decisions. This one is not just opinionated but wrong. `basic.publish` does not have a `queue` field on the wire and publishing does not happen to queues.

Some clients provide separate functions for publishing "directly" to queues (over the default exchange).

**Comment by Keruspe** [comment]
I think that’s actually a leftover, it sure should be fixed.
Can you send a PR?
