### ISSUE TITLE
Gracefully closing queues, channels and connections

### ISSUE THREAD

**Issue by Relrin** [sozu-proxy/lapin#91]
Hello!

I'm trying to write a small piece of code that will delete the queue and close the channel we have got an error on the linking with exchange point stage. For example, with the following code:
```rust
.and_then(move |channel| {
    channel.queue_bind(
        &queue_name_bind,
        &endpoint_link.get_response_exchange(),
        &endpoint_link.get_microservice(),
        &QueueBindOptions::default(),
        &FieldTable::new()
    )
        // Process the errors only when exchange point wasn't created yet
        .map_err(|err| {
            // Delete the recently created queue
            channel.queue_delete(&queue_name_bind, &QueueDeleteOptions::default()).map(move |_| {
                // Close the connection
                channel.close(INTERNAL_ERROR, "Connection closed: Invalid response exchange.").map(move |_| channel)
            })
        })
       // All is ready, go to the next step and re-use the channel with the next `.and_then` block 
        .map(|_| channel)
})
.map_err(|err| {
    let message = format!("Error during linking the response queue with exchange. Reason -> {}", err);
    error!("{}", message);
    err
})
```
I'm getting an error on the compile stage:
```
error[E0271]: type mismatch resolving `<[closure@src/engine/mod.rs:111:30: 117:22 channel:_, queue_name_bind:_] as std::ops::FnOnce<(std::io::Error,)>>::Output == std::io::Error`
   --> src/engine/mod.rs:102:14
    |
102 |             .and_then(move |channel| {
    |              ^^^^^^^^ expected struct `futures::Map`, found struct `std::io::Error`
    |
    = note: expected type `futures::Map<std::boxed::Box<futures::Future<Item=(), Error=std::io::Error>>, [closure@src/engine/mod.rs:113:100: 116:26 channel:_, err:_]>`
               found type `std::io::Error`
    = note: required because of the requirements on the impl of `futures::Future` for `futures::MapErr<std::boxed::Box<futures::Future<Item=(), Error=std::io::Error>>, [closure@src/engine/mod.rs:111:30: 117:22 channel:_, queue_name_bind:_]>`
```

How can I solve this issue, so that the error handling aren't expanding? Does the lapin provides any options for customizing behaviour (for example, client) so that it could close and delete everything if we've got a failure?

**Comment by michaelklishin** [comment]
I'm not sure what you mean by "error handling aren't expanding".

See server logs. Without knowing what kind of error that is I'm not sure how you can know much more.

On an unrelated note, closing channels with status code of "internal error" makes no sense. A failed `queue.delete` is not an "internal error". Not that it matters to RabbitMQ but

**Comment by michaelklishin** [comment]
My guess as to what is going on: you hit a channel exception that closes the channel (for instance, try deleting a queue that does not exist). Then you try to close the channel. Closing a channel that's not open is a connection-level exception after which RabbitMQ will close the connection => you observe an I/O error. Server logs can unambiguously prove this hypothesis right or wrong.

Most clients throw/return an error immediately when you attempt to use an already closed channel.
Not sure if Lapin does.

**Comment by Relrin** [comment]
This code was taken from my personal project and I'd like to write something like this for processing errors, because if we don't do it manually (deleting the queues, unbinding from exchange and so on), then the connection will be still alive, which isn't a good fit for me. And I'd like to go this way first of all because a proxy creates a separate connection per each message and follows Request / Response pattern. But if something goes wrong, we will just send the certain response to the client with a message like "Please, re-send the message one more time" and close everything that related to this connection / session.

I've got errors on this stage, when trying to bind a queue with a not declared exchange. Of course, I could add a call for this case and create it in code, but I'm expecting that everything already done on the RabbitMQ side and all required exchange point are created (via management plugin or was declared on the Docker image, so that it will created automatically).

**Comment by michaelklishin** [comment]
@Relrin server logs will clearly tell what the errors are. I'm not sure what kind of response you are looking but without knowing what exactly happened it likely won't be very informed.

**Comment by Relrin** [comment]
It have a sense, in general. However, the server in my case is a reverse proxy, which is going to hide a complexity and an access to message broker from a typical users, but let them send requests to this server instead via WebSockets in the certain format. That's why I'm only interested in sending to them the message with text "make an another attempt" instead. 

On the each step of chained futures we already know what was done before, first of all because they're chaining with `and_then` only when succeed the previous one, otherwise any other futures will be ignored.

**Comment by Relrin** [comment]
Okay. Right now I'm trying to deal with corner cases with the following code, which will delete the already existing queue (it's also seeing in management plugin) and close the channel as well:
```rust
.and_then(move |channel| {
    let queue_name_bind_copy = queue_name_bind.clone();
    let channel_copy = channel.clone();

    channel.queue_bind(
        &queue_name_bind,
        &endpoint_link.get_response_exchange(),
        &endpoint_link.get_microservice(),
        &QueueBindOptions::default(),
        &FieldTable::new()
    )
        // Process the errors only when exchange point wasn't created yet
        .or_else(move |err| {
            println!("inside or_else");
            let queue_delete_options = QueueDeleteOptions {
                if_unused: false,
                if_empty: false,
                ..Default::default()
            };

            channel_copy.queue_delete(&queue_name_bind_copy, &queue_delete_options)
                .and_then(move |_| {
                    println!("inside queue_delete");
                    channel_copy.close(200, "Connection closed: Invalid response exchange.")
                })
                .then(move |res| {
                    match res {
                        Ok(_) => println!("OK."),
                        Err(r) => println!("{:?}", r)
                    };
                    println!("inside then");
                    Err(err)
                })
        })
        .map(move |_| {
            println!("inside map");
            channel
        })
})
.map_err(|err| {
    let message = format!("Error during linking the response queue with exchange. Reason -> {}", err);
    error!("{}", message);
    err
})
```
But instead of closing everything correctly, I'm getting the situation when the potential error case must be executed:
```
Listening on: 0.0.0.0:8080
inside or_else
Error { repr: Custom(Custom { kind: Other, error: StringError("Could not purge queue: NotConnected") }) }
inside then
[2018-02-02][10:29:51][pathfinder::engine][ERROR] Error during linking the response queue with exchange. Reason -> failed to handle frame: NotConnected
[2018-02-02][10:29:52][pathfinder::engine][ERROR] Error during publishing a message. Reason -> failed to handle frame: NotConnected
[2018-02-02][10:29:52][pathfinder::engine][ERROR] Error during consuming the response message. Reason -> failed to handle frame: NotConnected
[2018-02-02][10:29:52][pathfinder::engine][ERROR] Error during sending a message to the client. Reason -> failed to handle frame: NotConnected
[2018-02-02][10:29:52][pathfinder::engine][ERROR] Error during deleting the queue. Reason -> failed to handle frame: NotConnected
[2018-02-02][10:29:52][pathfinder::engine][ERROR] Error during closing the channel. Reason -> failed to handle frame: NotConnected
```
Any ideas why the `queue_delete()` is failed here? As I had mentioned here, the queue is existing (like the channel and connection), but attempt to close all of those things  can't be reached.

**Comment by Relrin** [comment]
I figured out what's going with RabbitMQ, so:
1) When we're trying to bind a new exclusive queue (without auto-delete) to the not existing exchange, then we will have got an error of binding, that leads to failing a future that is handling this case. So, in RabbitMQ logs we're getting this:
```
2018-02-02 17:52:01.362 [info] <0.3699.0> accepting AMQP connection <0.3699.0> (172.21.0.3:43158 -> 172.21.0.2:5672)
2018-02-02 17:52:01.406 [info] <0.3699.0> connection <0.3699.0> (172.21.0.3:43158 -> 172.21.0.2:5672): user 'user' authenticated and granted access to vhost 'vhost'
2018-02-02 17:52:01.421 [error] <0.3708.0> Channel error on connection <0.3699.0> (172.21.0.3:43158 -> 172.21.0.2:5672, vhost: 'vhost', user: 'user'), channel 1:
operation queue.bind caused a channel exception not_found: no exchange 'open-matchmaking.responses.direct' in vhost 'vhost'
```
2) If we really want to close it anyway for the error case, then necessary to do it manually, via the closing channel/connection (so, just invoke `channel.close()` and doing anything else, right?) or via management plugin / HTTP request / rabbitmqctl using and so on. Does it correct, @michaelklishin ?
3) An attempt to invoke the `close()` method for a channel, when the connection in an "error state", leads also to an error:
```
Listening on: 0.0.0.0:8080
inside or_else
Error { repr: Custom(Custom { kind: Other, error: StringError("Could not close channel: NotConnected") }) }
inside then
[2018-02-02][17:52:01][pathfinder::engine][ERROR] Error in RabbitMQ client. Reason -> failed to handle frame: NotConnected
```
When the client code for processing the runtime errors is:
```rust
.and_then(move |channel| {
    let queue_name_bind_copy = queue_name_bind.clone();
    let channel_copy = channel.clone();

    channel.queue_bind(
        &queue_name_bind,
        &endpoint_link.get_response_exchange(),
        &endpoint_link.get_microservice(),
        &QueueBindOptions::default(),
        &FieldTable::new()
    )
        // Process the errors only when exchange point wasn't created yet
        .or_else(move |err| {
            println!("inside or_else");

            channel_copy.close(200, "Connection closed: Invalid response exchange.")
                .then(move |res| {
                    match res {
                        Ok(_) => println!("OK."),
                        Err(r) => println!("{:?}", r)
                    };
                    println!("inside then");
                    Err(err)
                })
        })
        .map(move |_| {
            println!("inside map");
            channel
        })
})

```
Can I somehow close the connection correctly, so that I won't close it via rabbitmqctl or UI or something else? @Geal @Keruspe

**Comment by Relrin** [comment]
Anybody have ideas what can be an issue here and why I can't delete the queue with closing the channel later?

**Comment by Keruspe** [comment]
I’m opening a new issue for the connection close missing and closing this one
